{
"sites": [
{"key": "lezhu","name": "选择","type": 1,"api": "http://pandown.pro/maoys/lezhu.php","searchable": 0,"quickSearch": 0,"filterable": 0},
{"key": "lezhu","name": "乐猪","type": 1,"api": "http://pandown.pro/maoys/lezhu.php","searchable": 1,"quickSearch": 1,"filterable": 0},
{"key": "dr_乐猪TV","name": "乐猪","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=乐猪TV","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key":"量子","name":"极速","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["国产剧","纪录片","足球","篮球","斯诺克","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","香港剧","韩国剧","欧美剧","台湾剧","日本剧","泰国剧","大陆综艺","日韩综艺","港台综艺","欧美综艺","国产动漫","日韩动漫","海外动漫"]},
{"key":"1080资源库","name":"1080p","type":1,"api":"https://api.1080zyku.com/inc/api_mac10.php","searchable":0,"quickSearch":0,"categories":["国产剧","综艺","动漫","动画片","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","韩国剧","欧美剧","香港剧","泰国剧","日本剧","港台剧"]},
{"key":"csp_xigua26","name":"西瓜","type":1,"api":"https://xigua26.com/api.php/provides/vod/","searchable":1,"quickSearch":1,"date":"2022-09-18 18:45:13"},
{"key": "dr_88看球","name": "看球吧","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=88看球","searchable": 0,"quickSearch": 0,"filterable": 0},
{"key": "dr_JRS看直播","name": "Jrs看直播","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=JRS看直播","searchable": 0,"quickSearch": 0,"filterable": 0},
{"key": "dr_310直播","name": "310直播","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=310直播","searchable": 0,"quickSearch": 0,"filterable": 0},
{"key": "dr_JRKAN直播","name": "球迷直播","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=JRKAN直播","searchable": 0,"quickSearch": 0,"filterable": 0},
{"key": "dr_抓饭体育","name": "抓饭体育","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=抓饭体育","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key":"zy_乱舞1","name":"🐧小Q","type":1,"api":"https://cms.json.vin/api.php/provide/vod/from/qq/?ac=list","searchable":1,"playUrl":"https://jx.jsonplayer.com/player/?url=","quickSearch":1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","电影","连续剧","综艺","动漫","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片"]},
{"key":"zy_乱舞2","name":"🍋小果","type":1,"api":"https://cms.json.vin/api.php/provide/vod/from/mgtv/?ac=list","searchable":1,"playUrl":"https://jx.jsonplayer.com/player/?url=","quickSearch":1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","电影","连续剧","综艺","动漫","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片"]},
{"key":"zy_乱舞4","name":"🆒小酷","type":1,"api":"https://cms.json.vin/api.php/provide/vod/from/youku/?ac=list","searchable":1,"playUrl":"https://jx.jsonplayer.com/player/?url=","quickSearch":1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","电影","连续剧","综艺","动漫","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片"]},
{"key":"zy_乱舞3","name":"🦊小狐","type":1,"api":"https://cms.json.vin/api.php/provide/vod/from/sohu/?ac=list","searchable":1,"playUrl":"https://jx.jsonplayer.com/player/?url=","quickSearch":1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","电影","连续剧","综艺","动漫","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片"]},
{"key": "红牛","name": "红牛","type": 1,"api": "https://www.hongniuzy2.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories":["国产剧","体育赛事","纪录片","港澳剧","日剧","韩剧","欧美剧","战争片","动作片","喜剧片","爱情片","科幻片","剧情片","战争片","综艺","动漫"]},
{"key":"草民","name": "️草民","type": 1,"api": "https://www.xsgj.net/api.php/provide/vod/","playUrl": "https://lziplayer.com/?url=","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["国产剧","动漫"]},
{"key":"百淘影视","name":"百淘","type":1,"api":"http://ys.58g8.com/api.php/provide/vod/","searchable":0,"quickSearch":0},
{"key":"资源","name":"百度","type":1,"api":"https://api.apibdzy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["大陆剧","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","港澳剧","韩剧","日剧","欧美剧","其他剧","大陆综艺","日韩综艺","港台综艺","悬疑片","欧美综艺","国产动漫","日韩动漫","欧美动漫","其他片","动画电影"]},
{"key": "dr_厂长资源","name": "厂长🌩","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=厂长资源","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_IMAX影视","name": "IMAX","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=IMAX影视","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_布雷蓝光","name": "布雷","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=布雷蓝光","searchable": 2,"quickSearch": 1,"filterable": 0},
{"key":"dr_蓝光","name":"蓝光","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=蓝光影院","searchable":1,"quickSearch":1,"filterable":0},
{"key":"dr_喵喵","name":"喵喵","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=喵喵","searchable":1,"quickSearch":1,"filterable":0,"categories":["电影","电视剧","综艺"]},
{"key":"dr_兔小贝","name":"兔小贝","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=兔小贝","searchable":1,"quickSearch":1,"filterable":0},
{"key":"dr_腾云驾雾","name":"腾云","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=腾云驾雾","searchable":1,"quickSearch":1,"filterable":0},
{"key":"dr_奇珍异兽","name":"奇珍","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=奇珍异兽","searchable":1,"quickSearch":1,"filterable":0}, 
{"key":"dr_莫扎兔","name":"莫扎兔","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=莫扎兔","searchable":1,"quickSearch":1,"filterable":0},
{"key": "dr_360影视","name": "360","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=360影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_人人影视","name": "人人🌩","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=人人影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_胖虎影视","name": "胖虎js🌾","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=胖虎影视&ext=txt/js/tg/胖虎影视.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_Nike影视","name": "Nikejs","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=Nike影视&ext=txt/js/tg/Nike影视.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_真不卡","name": "真不卡🌩","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=真不卡","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_乐猪TV","name": "乐猪js","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=乐猪TV&ext=txt/js/tg/乐猪TV.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_天空影视","name": "天空js","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=天空影视&ext=txt/js/tg/天空影视.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_在线之家","name": "在线js","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=在线之家","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_两个BT","name": "2BTjs","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=两个BT&ext=txt/js/tg/两个BT.js","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_69美剧","name": "美剧","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=69美剧","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_188看","name": "188看","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=188看","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_大米星球","name": "大米","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=大米星球","searchable": 2,"quickSearch": 0,"filterable": 0,"categories":["电影","电视剧","动漫","综艺"]},
{"key": "dr_8号影院","name": "8号影院","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=8号影院","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_BD360","name": "BD360","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=BD360","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_尘落影视","name": "尘落","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=尘落影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_农民影视","name": "农民影视","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=农民影视","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_盛世电影网","name": "盛世电影网","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=盛世电影网","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_影视工场","name": "影视工场","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=影视工场","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_热播库","name": "热播库","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=热播库","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_首播影院","name": "首播影院","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=首播影院","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_7喜影院","name": "7喜影院","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=7喜影院","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_星辰","name": "星辰","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=星辰","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_快看","name": "快看","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=快看","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_爱看","name": "爱看","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=爱看","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_量子影视","name": "量子","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=量子影视","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_骚火","name": "骚火","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=骚火","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_双十电影","name": "双十","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=双十电影","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_子子影视","name": "子子","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=子子影视","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_城市电影","name": "城市电影","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=城市电影","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_金曼影视","name": "金曼影视","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=金曼影视","searchable": 2,"quickSearch": 0,"filterable": 1},
{"key": "dr_酷奇MV","name": "酷奇MV","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=酷奇MV","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_爱车MV","name": "爱车MV","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=爱车MV","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key": "dr_DJ音乐","name": "DJ音乐🌩","type": 1,"api": "https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=DJ音乐","searchable": 2,"quickSearch": 0,"filterable": 0},
{"key":"zy-ffzy","name":"非凡","type":1,"api":"http://www.ffzy.tv/api.php/provide/vod/","searchable":1,"filterable":0,"changeable":1,"categories":["国产剧","国产动漫","大陆综艺","动作片","喜剧片","科幻片","恐怖片","爱情片","剧情片","战争片",
"记录片","欧美剧","香港剧","韩国剧","台湾剧","日本剧","海外剧","泰国剧","日韩动漫","欧美动漫","港台动漫","海外动漫","港台综艺","日韩综艺","欧美综艺"]},
{"key":"zy_乱舞8","name":"图图","type":1,"api":"https://ys.md214.cn/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1,"categories":["大陆剧","电影","连续剧","综艺","动漫","直播"]},
{"key":"四个圈影视","name":"四个圈","type":1,"api":"https://pg.fenwe078.cf/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories": ["电影","国产剧","港台剧","日韩剧","欧美剧","海外剧","国产动漫","日韩动漫","欧美动漫","综艺"]},
{"key":"快播","name":"快播","type":1,"api":"http://www.kuaibozy.com/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key":"酷点资源","name":"酷点","type":1,"api":"https://kudianzy.com/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key": "樱花资源","name": "樱花","type": 1,"api": "https://m3u8.apiyhzy.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories":["国产剧","综艺","动漫","动画电影","纪录片","动作片","犯罪片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","韩国剧","欧美剧","香港剧","海外剧","日本剧","港台综艺","国产动漫","日本动漫","欧美动漫"]},
{"key":"飞速资源","name":"飞速","type":1,"api":"https://www.feisuzy.com/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key":"卧龙资源","name":"卧龙","type":1,"api":"https://collect.wolongzyw.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["国产剧","香港剧","纪录片","篮球","足球","大陆综艺","欧美动漫","电影解说","短片","动画片","动作片","古装片","历史片","家庭片","惊悚片","犯罪片","喜剧片","爱情片","科幻片","恐怖片","悬疑片","剧情片","战争片","台湾剧","韩国剧","欧美剧","泰国剧","海外剧","日本剧","大陆综艺","港台综艺","韩国综艺","欧美综艺","国产动漫","日本动漫","欧美动漫"]},
{"key": "闪电资源","name": "闪电","type": 1,"api": "http://sdzyapi.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories":["国产剧","港剧","纪录片","篮球","足球","大陆综艺","斯诺克","电影解说","短片","动画片","动作片","演唱会","冒险片","预告片","惊悚片","犯罪片","喜剧片","爱情片","奇幻片","恐怖片","悬疑片","剧情片","战争片","台剧","韩剧","欧美剧","泰剧","海外剧","日剧","大陆综艺","港台综艺","日韩综艺","欧美综艺","国产动漫","日韩动漫","港台动漫","欧美动漫"]},
{"key": "飞速资源","name": "飞速资源(切)","type": 1,"api": "https://www.feisuzy.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories": ["国产剧","香港剧","台湾剧","日本剧","韩国剧","欧美剧","纪录片","国产动漫","日韩动漫","欧美动漫","大陆综艺","港台综艺"]},
{"key": "光速","name": "光速","type": 1,"api": "https://api.guangsuapi.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories":["大陆剧","体育赛事","纪录片","港澳剧","日剧","韩剧","欧美剧","战争片","动作片","喜剧片","爱情片","科幻片","剧情片","战争片","综艺","动漫"]},
{"key":"影图","name":"影图","type":1,"api":"https://cj.vodimg.top/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key": "蓝光", "name": "蓝光/解析", "type": 1, "api": "http://playersll.gaoxin155.com.cn/api.php/provide/vod/", "searchable": 1, "quickSearch": 1, "filterable": 0,"playerType":2  },
{"key": "无名","name": "无名/解析", "type": 1,"api": "http://124.220.183.81:83/api.php/provide/vod/", "searchable": 1,"quickSearch": 1, "filterable": 0,"playerType":2 },
{"key": "可米", "name": "可米/解析", "type": 1,"api": "https://cj.kemi.lol/api.php/provide/vod/", "searchable": 1, "quickSearch": 1, "filterable": 0,"playerType":2 },
{"key": "腾讯资源","name": "️🐧腾讯","type": 1,"api": "http://anltv.cn/api.php/provide/vod/from/qq/?at/xml/","playUrl":"https://jxdp.codermart.net/?url=","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片","综艺","动漫"]},
{"key": "芒果资源","name": "️🥭芒果","type": 1,"api": "http://anltv.cn/api.php/provide/vod/from/mgtv/?at/xml/","playUrl":"","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片","综艺","动漫"]},
{"key": "爱奇艺资源","name": "️🥝爱奇艺","type": 1,"api": "http://anltv.cn/api.php/provide/vod/from/qiyi/?at/xml/","playUrl":"https://jxdp.codermart.net/?url=","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片","综艺","动漫"]},
{"key": "优酷资源","name": "️👔优酷","type": 1,"api": "http://anltv.cn/api.php/provide/vod/from/youku/?at/xml/","playUrl":"https://www.cgdyw.net/jiexi/jiexi-gf/?url=","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片","综艺","动漫"]},
{"key": "搜狐资源","name": "️🦊搜狐","type": 1,"api": "http://anltv.cn/api.php/provide/vod/from/sohu/?at/xml/","playUrl":"https://jx.xmflv.com/?url=","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["国产剧","韩国剧","香港剧","台湾剧","欧美剧","动作片","科幻片","战争片","奇幻片","喜剧片","爱情片","恐怖片","犯罪片","悬疑片","惊悚片","剧情片","冒险片","记录片","综艺","动漫"]},
{"key": "明帝","name": "️明帝","type": 1,"api": "https://ys.md214.cn/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["连续剧","电影","综艺","动漫","直播"]},
{"key":"鸡婆","name": "️jipo","type": 1,"api": "https://www.jipo.tv/api.php/provide/vod","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":[]},
{"key":"天堂","name":"天堂","type":1,"api":"http://vipmv.cc/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key":"小鸟动漫","name":"动漫","type":1,"api":"http://xydm.baicai.buzz/api.php/provide/vod/","searchable":0,"quickSearch":0},
{"key":"猫咪","name":"猫咪","type":1,"api":"http://zy.xiaomaomi.cc/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key":"爱酷","name":"爱酷","type":1,"api":"https://www.zhanlangbu.com/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key":"木子","name":"电视直播","type":1,"api":"https://mzkj.maccms.cf/api.php/provide/vod/","searchable":0,"quickSearch":0,"categories":["直播","电影","连续剧","综艺","动漫","哔哩哔哩"]},
{"key": "淘片","name": "淘片","type": 0,"api": "https://taopianzy.com/home/cjapi/as/mc10/vod/xml/m3u8","categories": []},
{"key": "U酷","name": "U酷","type": 1,"api": "https://api.ukuapi.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories":["国产剧","纪录片","综艺","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","港澳剧","日剧","欧美剧"]},
{"key":"77","name":"77","type":1,"api":"http://121.37.131.75/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["国产剧","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","韩剧","泰剧","动漫"]},
{"key":"天空","name":"天空","type":1,"api":"https://api.tiankongapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1},
{"key": "鱼乐","name": "鱼乐","type": 1,"api": "https://api.ylzy1.com/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"categories":["纪录片","国产剧","综艺","动漫","连续剧","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","香港剧","韩国剧","美国剧"]},

{"key":"新浪","name":"新浪☕","type":1,"api":"http://api.xinlangapi.com/xinlangapi.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["大陆剧","体育","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","港澳剧","台湾剧","欧美剧","韩剧","综艺","动漫","日剧","泰剧","动漫电影"]}


   
],
"flags": ["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu","bilibili","le","duoduozy","renrenmi","优酷","芒果","腾讯","爱奇艺","奇艺","ltnb","rx","CL4K","xfyun","wuduzy","fuckapp","ftqp2","ftqp3","ftqp4",   "ftqp5"],
"lives": [
{"group": "央视","channels": [
{"name":"CCTV1","urls":["http://39.134.66.48/PLTV/88888888/224/3221225816/index.m3u8"]},
{"name":"CCTV2","urls":["http://39.134.115.163:8080/PLTV/88888910/224/3221225619/index.m3u8$超清1080P"]},
{"name":"CCTV3","urls":["http://39.134.24.166/dbiptv.sn.chinamobile.com/PLTV/88888888/224/3221226397/1.m3u8$超清1080P"]},
{"name":"CCTV4","urls":["http://39.134.115.163:8080/PLTV/88888910/224/3221225621/index.m3u8$超清1080P"]},
{"name":"CCTV5","urls":["http://39.134.24.161/dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226395/index.m3u8?"]},
{"name":"CCTV5+","urls":["http://39.134.115.163:8080/PLTV/88888910/224/3221225649/index.m3u8"]},
{"name":"CCTV6","urls":["http://gslbserv.itv.cmvideo.cn/index.m3u8?channel-id=ystenlive&Contentid=1000000001000016466&livemode=1&stbId=4$超清1080P"]},
{"name":"CCTV7","urls":["http://39.134.67.226/PLTV/88888888/224/3221225671/index.m3u8$超清1080P"]},
{"name":"CCTV8","urls":["http://39.135.138.60:18890/PLTV/88888910/224/3221225635/index.m3u8$超清1080P"]},
{"name":"CCTV9","urls":["http://39.134.67.226/PLTV/88888888/224/3221225676/index.m3u8$超清1080P"]},
{"name":"CCTV10","urls":["http://39.134.66.66/PLTV/88888888/224/3221225677/index.m3u8$超清1080P"]},
{"name":"CCTV11","urls":["http://39.134.67.226/PLTV/88888888/224/3221225517/index.m3u8$超清1080P"]},
{"name":"CCTV12","urls":["http://39.134.67.226/PLTV/88888888/224/3221225669/index.m3u8$超清1080P"]},
{"name":"CCTV13","urls":["http://39.134.67.226/PLTV/88888888/224/3221225812/index.m3u8$超清1080P"]},
{"name":"CCTV14","urls":["http://39.134.67.226/PLTV/88888888/224/3221225674/index.m3u8$超清1080P"]},
{"name":"CCTV15","urls":["http://39.134.115.163:8080/PLTV/88888910/224/3221225641/index.m3u8$超清1080P"]},
{"name":"CCTV16","urls":["http://39.135.138.58:18890/TVOD/88888910/224/3221226230/index.m3u8$超清1080P"]},
{"name":"CCTV17","urls":["http://39.134.66.110/PLTV/88888888/224/3221225708/index.m3u8$超清1080P"]},

{"name":"CCTV1","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226016/index.m3u8"]},
{"name":"CCTV2","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225588/index.m3u8"]},
{"name":"CCTV3","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226021/index.m3u8"]},
{"name":"CCTV4","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226007/index.m3u8"]},
{"name":"CCTV5","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226019/index.m3u8"]},
{"name":"CCTV5+","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225603/index.m3u8"]},
{"name":"CCTV6","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226010/index.m3u8"]},
{"name":"CCTV7","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225733/index.m3u8"]},
{"name":"CCTV8","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226008/index.m3u8"]},
{"name":"CCTV9","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225734/index.m3u8"]},
{"name":"CCTV10","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225730/index.m3u8"]},
{"name":"CCTV11","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225597/index.m3u8"]},
{"name":"CCTV12","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225731/index.m3u8"]},
{"name":"CCTV13","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226011/index.m3u8"]},
{"name":"CCTV14","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225732/index.m3u8"]},
{"name":"CCTV15","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225601/index.m3u8"]},
{"name":"CCTV16","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226100/index.m3u8"]},
{"name":"CCTV17","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225765/index.m3u8"]}
]},
{"group": "卫视","channels": [
{"name":"湖南卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225610/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226053/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226045/index.m3u8"]},
{"name":"东南卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226079/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225620/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226041/index.m3u8"]},
{"name":"深圳卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225739/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226111/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226084/index.m3u8"]},
{"name":"广东卫视","urls":["http://111.20.33.93/PLTV/88888893/224/3221226216/index.m3u8","http://111.20.33.93/TVOD/88888893/224/3221226216/index.m3u8"]},
{"name":"江苏卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225613/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226099/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226017/index.m3u8"]},
{"name":"东方卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225735/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226082/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226031/index.m3u8"]},
{"name":"北京卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225728/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226064/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226020/index.m3u8"]},
{"name":"浙江卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225612/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226056/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226034/index.m3u8"]},
{"name":"吉林卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226047/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226035/index.m3u8"]},
{"name":"四川卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226096/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226081/index.m3u8"]},
{"name":"天津卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225740/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226073/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226052/index.m3u8"]},
{"name":"安徽卫视","urls":["http://111.20.33.93/PLTV/88888893/224/3221226196/index.m3u8","http://111.20.33.93/TVOD/88888893/224/3221226196/index.m3u8"]},
{"name":"山东卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226067/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226078/index.m3u8"]},
{"name":"江西卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226085/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226075/index.m3u8"]},
{"name":"河北卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226059/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225623/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226069/index.m3u8"]},
{"name":"河南卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226108/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226063/index.m3u8"]},
{"name":"海南卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226102/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225639/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226043/index.m3u8"]},
{"name":"湖北卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225627/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226088/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226046/index.m3u8"]},
{"name":"贵州卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226105/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225626/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226051/index.m3u8"]},
{"name":"重庆卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226062/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225618/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226066/index.m3u8"]},
{"name":"黑龙江卫视","urls":["http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226014/index.m3u8","http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226033/index.m3u8"]}
]},
{"group": "地方","channels": [
{"name":"凤凰中文","urls":["http://play-live.ifeng.com/live/06OLEGEGM4G.m3u8"]},
{"name":"凤凰中文","urls":["http://playtv-live.ifeng.com/live/06OLEGEGM4G.m3u8"]},
{"name":"凤凰中文","urls":["http://playtv-live.ifeng.com/live/06OLEGEGM4G_tv1.m3u8"]},
{"name":"凤凰中文","urls":["http://playtv-live.ifeng.com:80/live/06OLEGEGM4G_tv2.m3u8"]},
{"name":"凤凰中文","urls":["https://playtv-live.ifeng.com/live/06OLEGEGM4G_tv2.m3u8"]},
{"name":"凤凰资讯","urls":["http://playtv-live.ifeng.com/live/06OLEEWQKN4.m3u8"]},
{"name":"凤凰资讯","urls":["https://playtv-live.ifeng.com/live/06OLEEWQKN4_tv1.m3u8"]},
{"name":"凤凰资讯","urls":["http://playtv-live.ifeng.com/live/06OLEEWQKN4_tv2.m3u8"]},
{"name":"翡翠台","urls":["http://jyjxy.7766.org:808/hls/36/index.m3u8"]},
{"name":"广东珠江","urls":["http://mmitv.top/pltv/itouchtv.php?id=gdzj"]},
{"name":"广东珠江","urls":["http://9.zhxinda.xyz/gdtv.php?pk=1183$高清720P"]},
{"name":"广东体育","urls":["http://d953c45ae944de6f1329edb2802f51f4.v.smtcdns.net/4403-tx.otvstream.otvcloud.com/otv/skcc/live/channel34/2300.m3u8"]}
]}
],
"parses": [
{"name":"选解析➡","type":3,"url":"Demo"},
{"name": "首选", "type": 0, "url": "https://dm.xmflv.com:4433/?url="},
{"name": "玩的嗨", "type": 0, "url": "http://tv.wandhi.com/go.html?url="},
{"name":"纯净1","url":"https://z1.m1907.cn/?jx=","mobile":1},
{"name":"B站1","url":"https://jx.bozrc.com:4433/player/?url=","mobile":1},
{"name":"ckmov","url":"https://www.ckmov.vip/api.php?url=","mobile":0},
{"name":"CK","url":"https://www.ckplayer.vip/jiexi/?url=","mobile":0},
{"name":"爱豆","url":"https://jx.aidouer.net/?url=","mobile":1},
{"name":"BL","url":"https://vip.bljiex.com/?v=","mobile":0},
{"name":"PM","url":"https://www.playm3u8.cn/jiexi.php?url=","mobile":0},
{"name":"虾米","url":"https://jx.xmflv.com/?url=","mobile":0},
{"name":"OK","url":"https://okjx.cc/?url=","mobile":1},
{"name":"猫影视","type":1,"url":"https://api.maoyingshi.cc/home/api?type=ys&uid=3266342&key=clmqrwCEFHJR025789&url="},
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"冰豆","url":"https://api.qianqi.net/vip/?url=","mobile":0},
{"name":"CHok","url":"https://www.gai4.com/?url=","mobile":1},
{"name":"H8","url":"https://www.h8jx.com/jiexi.php?url=","mobile":0},
{"name":"JY","url":"https://jx.playerjy.com/?url=","mobile":0},
{"name":"解析","url":"https://ckmov.ccyjjd.com/ckmov/?url=","mobile":0},
{"name":"解析la","url":"https://api.jiexi.la/?url=","mobile":0},
{"name":"MAO","url":"https://www.mtosz.com/m3u8.php?url=","mobile":0},
{"name": "一看", "url": "https://analysis.yikan.one/analysis/player/analysis.php?v=" },
{"name":"4K","url":"https://jx.4kdv.com/?url=","mobile":1},
{"name":"盘古","url":"https://www.pangujiexi.cc/jiexi.php?url=","mobile":0},
{"name":"思古3","url":"https://jsap.attakids.com/?url=","mobile":1},
{"name": "极速", "url": "http://vip.mufeifan.com.cn/1/vip/3/?url=" },
{"name":"诺讯TXYK","url":"https://www.nxflv.com/?url=","mobile":0},
{"name":"🍓TXAQY","url":"https://h5.freejson.xyz/player/?url="}, 
{"name":"🍓TX","url":"https://m2090.com/?url="},
{"name":"🍓TXAQY","url":"https://dm.xmflv.com:4433/?url="}, 
{"name":"🍓TX","url":"https://jx.bozrc.com:4433/player/?url="}, 
{"name":"🍓TXAQY","url":"http://1.117.152.239:39000/?url="},
{"name":"🍓TXAQY","url":"http://newjiexi.gotka.top/keyu3.php?url="},
{"name":"人人迷","url":"https://jx.blbo.cc:4433/?url="},
{"name":"听乐","url":"https://jx.dj6u.com/?url="},
{"name":"QIM解12","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{ "name": "parw", "url": "https://jx.parwix.com:4433/player/?url=" },  
{"name": "nbxm","type":0,"url": "https://jx.xmflv.com/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "芒果VIP","type": 0,"url": "https://sb.5gseo.net/?url="},
{"name": "通用vip","type": 0,"url": "https://www.administratorw.com/video.php?url="},
{"name": "芒果","type": 0,"url": "http://47.100.138.210:92/?url="},
{"name":"bozrc","type":0,"url":"https://jx.bozrc.com:4433/player/?url="},
{"name":"刚刚","type":0,"url": " https://vip.fuqizhishi.com/?v="},
{"name":"OK解析","type":0,"url":"https://okjx.cc/?url="},
 {"name":"aidou","type":0,"url":"https://jx.aidouer.net/?url="},
{"name":"M3U8","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"laob","type":0,"url": "https://vip.laobandq.com/jiexi.php?url="},
{"name":"盘古","type":0,"url":"https://go.yh0523.cn/y.cy?url="},
{"name":"夜幕","type":0,"url":"https://www.yemu.xyz/?url="},
{"name":"铭人","type":0,"url":"https://parse.123mingren.com/?url="},
{"name": "nb最强","type":0,"url": "https://wds.ecsxs.com/217915.html?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "nbmv","type":0,"url": "https://jx.xmflv.vip/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "nbu1","type":0,"url": "https://api.u1o.net/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "parwix","type":0,"url": "https://jx.parwix.com:4433/player/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "atta","type":0,"url": "https://jsap.attakids.com/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "kpez","type":0,"url": "https://www.kpezp.cn/jlexi.php?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"QIM解04","type":1,"url":"http://150.230.216.174/tvjx.php?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"QI解06","type":1,"url":"http://150.230.216.174/tvjx.php?url=","ext":{"flag":["renrenmi","qq","腾讯","youku","优酷","mgtv","芒果","xigua","西瓜"]}},
{"name":"365","type":0,"url": "https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"QIM解13","type":0,"url":"https://jx.parwix.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"QIM解14","type":0,"url":"https://jx.parwix.com:4433/player/analysis.php?v=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name": "3","type": 1,"url": "https://api.m3u8.tv:5678/home/api?type=ys&uid=1931000&key=gktuvyzABEORSYZ135&url=","ext":{"flag":["youku","优酷","qq","腾讯","mgtv","芒果"]}},
{"name":"15","url":"https://vip.legendwhb.cn/m3u8.php?url="},
{"name": "6","type": 1,"url": "http://api.vip123kan.vip/?url=","ext":{"flag":["qiyi","爱奇艺","奇艺","mgtv","芒果","youku","优酷","pptv","PPTV"]}},
{"name": "11","type": 1,"url": "https://json.hfyrw.com/mao.go?url=","ext":{"flag":["ltnb","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视"]}},
{"name": "7","type": 1,"url": "http://json.hfyrw.com:9501/mao.go?url=","ext":{"flag":["ltnb","youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"王牌","type":1,"url":"https://za.kuanjv.com/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜"]}},
{"name":"15","type":1,"url":"https://app.iminna.com/jx/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "2","type": 1,"url": "https://za.kuanjv.com/?url=","ext":{"flag":["qiyi","爱奇艺","奇艺","qq","腾讯","mgtv","芒果","xigua","西瓜","letv","乐视"]}},
{"name": "10","type": 1,"url": "https://vip.legendwhb.cn/m3u8.php?url="},
{"name": "5","type": 1,"url": "https://svip.rongxingvr.top/api/?key=niBgMGXVdCQhsmeEBK&url="},
{"name": "8","type": 1,"url": "https://json.5lp.net/json.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","pptv","PPTV","bilibili","哔哩哔哩","哔哩","renrenmi","rx","rongxing"]}},
{"name": "13","type": 1,"url": "https://www.aiaine.com/api/?key=kVqmG5dAQ5dZTcECw8&url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "4","type": 1,"url": "http://103.40.240.46/jh/?url=","ext":{"flag":["renrenmi","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","xigua","西瓜","letv","乐视","bilibili","哔哩哔哩","哔哩"]}},
{"name": "9","type": 1,"url": "https://json.pangujiexi.com:12345/json.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","sohu"]}},
{"name": "14","type": 1,"url": "https://vip.rongxingvr.top/api/?type=ys&key=JJEZkZIhzkA4cUtBfR&url=","ext":{"flag":["ltnb","rx","qiyi","爱奇艺","qq","奇艺","sohu","letv","youku","优酷","mgtv","芒果"]}},
{"name":"aiaine02","type":1,"url":"https://vip.aiaine.com/api/?key=8FN8gNAySnvJiMllxZ&url=","ext":{"flag":["ltnb","renrenmi","weiyun"]}},
{"name":"jx165","type":1,"url":"https://ltjx.kuaixiao.vip/home/api?type=ys&uid=506916&key=dlmpwBHIKLMPQRVW23&url=","ext":{"flag":["ltnb"]}},
{"name":"OJBK","type":0,"url":"https://jmwl.qd234.cn/v/?v=","ext":{"flag":["ltnb","renrenmi","rx","xfyun","muxm3u8","xigua","xueren","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩","pptv","PPTV","sohu","letv"]}},
{"name":"M117","type":0,"url":"http://1.117.152.239:39000/?url="},
{"name": "parwix","type": 0,"url": "https://jx.parwix.com:4433/player/?url="},
{"name": "xm","type": 0,"url": "https://jx.xmflv.com/?url="},
{"name": "nbok","type": 0,"url": "https://okjx.cc/?url="},
{"name":"zui","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name": "nbmv","type": 0,"url": "https://jx.xmflv.vip/?url="}
],
"ijk": [
{"group": "软解码","options": [
{"category": 4,"name": "opensles","value": "0"},
{"category": 4,"name": "overlay-format","value": "842225234"},
{"category": 4,"name": "framedrop","value": "1"},
{"category": 4,"name": "soundtouch","value": "1"},
{"category": 4,"name": "start-on-prepared","value": "1"},
{"category": 1,"name": "http-detect-range-support","value": "0"},
{"category": 1,"name": "fflags","value": "fastseek"},
{"category": 2,"name": "skip_loop_filter","value": "48"},
{"category": 4,"name": "reconnect","value": "1"},
{"category": 4,"name": "max-buffer-size","value": "5242880"},
{"category": 4,"name": "enable-accurate-seek","value": "0"},
{"category": 4,"name": "mediacodec","value": "0"},
{"category": 4,"name": "mediacodec-auto-rotate","value": "0"},
{"category": 4,"name": "mediacodec-handle-resolution-change","value": "0"},
{"category": 4,"name": "mediacodec-hevc","value": "0"}]},
{"group": "硬解码","options": [
{"category": 4,"name": "opensles","value": "0"},
{"category": 4,"name": "overlay-format","value": "842225234"},
{"category": 4,"name": "framedrop","value": "1"},
{"category": 4,"name": "soundtouch","value": "1"},
{"category": 4,"name": "start-on-prepared","value": "1"},
{"category": 1,"name": "http-detect-range-support","value": "0"},
{"category": 1,"name": "fflags","value": "fastseek"},
{"category": 2,"name": "skip_loop_filter","value": "48"},
{"category": 4,"name": "reconnect","value": "1"},
{"category": 4,"name": "max-buffer-size","value": "5242880"},
{"category": 4,"name": "enable-accurate-seek","value": "0"},
{"category": 4,"name": "mediacodec","value": "1"},
{"category": 4,"name": "mediacodec-auto-rotate","value": "1"},
{"category": 4,"name": "mediacodec-handle-resolution-change","value": "1"},
{"category": 4,"name": "mediacodec-hevc","value": "1"}]}],

"ads": ["mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com",
"cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com",
"xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com",
"xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com",
"z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn",
"s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com",
"cms.qdwght.com"],
"spider": "https://codeberg.org/xxpctv/qmleyuandyingxiqu/raw/branch/master/listings/my275.html;md5;C21E26F56D8A11A169B11DA5C875DF93",
"wallpaper":"http://www.kf666888.cn/api/tvbox/img"

}