{
	"spider": "./Yoursmile3FE.jar;md5;3E0751CD3D758FB90B68F8E53808C3FE",
	"wallpaper": "https://tuapi.eees.cc/api.php?category=fengjing&type=302",
"sites":[
{"key":"csp_DouDou","name":"🎧豆瓣┃评分","type":3,"api":"csp_DouDou","searchable":0,"quickSearch":0,"filterable":1},
{"key":"csp_XBPQ_预告0308","name":"🍬预告片","type":3,"api":"csp_XBPQ","playerType":2,"ext":{"首页":"正在热映","图片代理":"","分类url":"https://movie.douban.com/{cateId}/;;aRC","分类":"即将上映$cinema/later#正在热映$cinema/nowplaying","数组":"class=\"item mod &&</ul>||正在热映--class=\"list-item&&</ul>","图片":"src=\"&&\"","标题":"\"intro\">&&</a>","链接":"href=\"&&\"","副标题":"data-score=\"&&\"+class=\"release-date\">&&</li>","播放数组":"<li class=\"video&&</li>","播放列表":"<a&&</a>","播放标题":"alt=\"&&\"","播放链接":"https://m.douban.com+href=\"&&\""}},
{"key": "T4-yugaopian","name": "🎬️预告片t4","type": 4,"api": "https://catbox.n13.club/t4/yugaopian.php","searchable": 1,"quickSearch": 1,"filterable": 1,"changeable": 0,"ext": true},
{"key":"广播频道","name":"📡广播电台","type":3,"api":"./live2mv.js","changeable":0,"ext":"广播电台$./广播频道.txt"},
{"key":"则奇0323","name":"🍏秒播(XBPQ)","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":{"分类":"动画&电影&国产动漫&日韩动漫&国产剧&喜剧片&爱情片&恐怖片&战争片&科幻片&动作片&综艺&欧美剧&港台剧&日韩剧","分类值":"33&1&75&76&14&22&26&36&25&30&23&69&15&16&62","分类url":"https://api.zeqaht.com/api.php/provide/vod/?ac=list&ac=detail&t={cateId}&pg={catePg}","数组二次截取":"list\":[&&]","数组":"{&&}[不包含:]","图片":"vod_pic\":\"&&\"","标题":"vod_name\":\"&&\"","副标题":"+vod_remarks\":\"&&\"","链接":"https://api.zeqaht.com/api.php/provide/vod/?ac=list&ac=detail&ids=+vod_id\":&&,","搜索url":"https://api.zeqaht.com/api.php/provide/vod?ac=detail&wd={wd}","搜索模式":"1","搜索二次截取":"list\":[&&]","搜索数组":"{&&}[不包含:]","搜索图片":"vod_pic\"*\"&&\"","搜索标题":"vod_name\"*\"&&\"","搜索副标题":"type_name\":\"&&\"","搜索链接":"https://api.zeqaht.com/api.php/provide/vod/?ac=list&ac=detail&ids=+vod_id\":&&,","影片类型":"vod_class\"*\"&&\"","导演":"vod_director\"*\"&&\"","主演":"vod_actor\"*\"&&\"","简介":"vod_content\"*\"&&\"","线路二次截取":"\"list\":[&&]","线路数组":"\"vod_play_from\":&&,","线路标题":"\"&&\"","播放数组":"vod_play_url\":&&,[替换:\">>链表题#$>>题链#\\#>>链表表题]","播放二次截取":"","播放列表":"表&&表","播放标题":"题&&题","播放链接":"链&&链","嗅探词":".m3u8","播放请求头":"User-Agent$Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36#Origin$www.whbax.cn#Referer$www.whbax.cn#Cookie$PHPSESSID=7da46a353cf8bac46b4f8226f06042ad","免嗅":"0"},"jar": "./XBPQ (0322).jar;md5;BB155C3F0133BBCE4756AD52003F5968"},
{"key": "秒播0402","name": "⚡秒播","type": 3,"api": "csp_XBPQ","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://notabug.org/xxpctv/dz/raw/master/py/秒播影视cj.json"},
{"key":"酷看0403","name":"🍈酷看","type":3,"api":"csp_Kkys","searchable":1,"quickSearch":1,"filterable":1,"jar":"./danmu.jar;md5;1D0A74FF670D78850FD443840FB66C88"},
{"key": "酷看","name": "🍈酷看2","type": 3,"api": "csp_Kkys","searchable": 1,"quickSearch": 1,"changeable": 1,"jar": "./kkys.jar;md5;D275081B5B9F999614A1930AA7599CB9"},
{"key":"歌曲0222","name":"🎙️歌曲","type":3,"api":"csp_Bili","ext":"./bili歌曲.json"},
{"key":"360ba_open0309","name":"🐳粤语直播","type":3,"playerType":"1","api":"./360ba_open.js"},
{"key":"yinyuetai_open0309","name":"🐳音悦台","type":3,"playerType":"1","api":"./yinyuetai_open.js"},
{"key": "T4-360kq0331","name": "⛹️粤语直播2","type": 4,"api": "https://catbox.n13.club/t4/360kq.php","searchable": 1,"quickSearch": 1,"filterable": 1,"changeable": 0,"ext": true},
{"key": "310直播0417","name": "💥310直播","type": 3,"api": "https://ghss.lan2wan.top/raw.githubusercontent.com/gaotianliuyun/gao/master/lib/drpy2.min.js","changeable": 0,"style": {"type": "rect","ratio": 1},"ext": "https://ghss.lan2wan.top/raw.githubusercontent.com/gaotianliuyun/gao/master/js/310直播.js"},
{"key": "Yinyuetai","name": "🛰音悦台┃音乐┃MV","type": 3,"api": "csp_Yinyuetai","searchable": 1,"changeable": 0,"jar": "./fangniu.jar;md5;91DE2C2701014CE63FFF81FFB420E029"},
{"key": "tjbook","name": "🍬手机听书","type": 3,"api": "csp_Bili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "./tjbook.json"},
{"key":"360","name":"💘360(d)","type":3,"api":"csp_SP33","searchable":1,"quickSearch":1,"filterable":1,"changeable":0},
{"key":"360kan_open2","name":"🐳360kan","type":3,"api":"./360kan_open.js"},
{"key": "T4-jgys","name": "🛰极光t4","type": 4,"api": "https://catbox.n13.club/t4/jiguang.php","searchable": 1,"quickSearch": 1,"filterable": 1,"changeable": 0,"ext": true},
{"key": "csp_Mp4Mov","name": "🧲Mp4电影","type": 3,"api": "csp_Mp4Mov","searchable": 1,"quickSearch": 1,"filterable": 1,"jar": "./cili.jar;md5;AB7A2BF5947C745657F25C80B337224B"},
{"key": "两个BT0427","name": "😊两个BT","type": 3,"api": "csp_XBPQ","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./bttwoo.json"},
{"key": "黑狐","name": "🦊黑狐XB","type": 3,"searchable": 1,"quickSearch": 1,"playerType": "1","api": "csp_XBPQ","ext": {"站名":"黑狐影院","主页url":"http://fagmn.com","数组":"class=\"stui-vodlist__box\"&&</a","图片":"data-original=\"&&\"","标题":"title=\"&&\"","链接":"href=\"&&\"","嗅探词":".m3u8#v3.huoshanvod.com#v3-dy-o.zjcdn#sf16-sg.larksuitecdn.com#v.kd1.qq.com","过滤词":"/hls/#php","副标题":"<span class=\"pic-text text-right\">&&</span>","搜索url":"http://fagmn.com/search.php;post;searchword={wd}","搜索模式":"1","搜索数组":"<a class=\"v-thumb stui-vodlist__thumb&&</a>","搜索图片":"data-original=\"&&\"","搜索标题":"title=\"&&\"","搜索链接":"href=\"&&\"","搜索副标题":"<span class=\"pic-text text-right\">&&</span>","搜索后缀":"/view/","线路数组":"href=\"#down&&/a>[替换:奇异视频>>黑狐一线#优酷视频>>黑狐二线#搜狐视频>>黑狐三线#咪咕视频>>黑狐四线]","线路标题":">&&<","播放数组":"class=\"stui-content__playlist clearfix&&</ul>","状态":"地区：&&</p>","导演":"导演：&&</p>","主演":"主演：&&</p>","简介":"简介：&&</div>","播放列表":"<a&&/a>","播放标题":">&&<","播放链接":"href=\"&&\"","免嗅":"0","分类":"电影$1#电视剧$2#动漫$3#综艺$4","分类url":"http://fagmn.com/list/{cateId}_{catePg}.html?order=time"}},

{"key":"drpy_js_酷吧0305","name":"酷吧4k|磁","type":3,"api":"./drpy2.min.js","ext":"./kuba.js", "quickSearch":1, "changeable":1, "timeout":60},
{"key":"新片场_30210","name":"📻新片场","type":"3","api":"./drpy2.min.js","ext":"https://ghproxy.net/https://raw.githubusercontent.com/xxpctv/dr_py/main/js/新片场.js"},
{"key":"荐片_30210","name":"📻荐片","type":"3","api":"./drpy2.min.js","ext":"https://ghproxy.net/https://raw.githubusercontent.com/xxpctv/dr_py/main/js/荐片.js"},
{"key":"南瓜影视_30210","name":"📻南瓜影视","type":"3","api":"./drpy2.min.js","ext":"https://ghproxy.net/https://raw.githubusercontent.com/xxpctv/dr_py/main/js/南瓜影视.js"},
{"key":"996影视","name":"📻996","type":"3","api":"./drpy2.min.js","ext":"https://ghproxy.net/https://raw.githubusercontent.com/xxpctv/dr_py/main/js/996影视.js"},
{"key":"荐0307","name":"Ⓜ️荐片1","type":3,"api":"./drpy2.min.js","playerType":"1","searchable":1,"quickSearch":1,"filterable":1,"ext":"./jp.js"},
{"key":"荐片1207","name":"Ⓜ️荐片2","type":3,"api":"csp_JianPian","playerType":1,"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://ownjpykxttjzuhy.jiesiwa.com","jar": "./Spider (jpxbpxyq).jar;md5;5E5B4B199219D78C20C989EEB71334CD"},
{"key":"6V新版[0101]","name":"🧲6V新[js]","type":3,"api":"./drpy2.min.js","searchable":1,"quickSearch":1,"changeable":0,"ext":"./6V新[磁].js", "timeout":30},
{"key": "csp_XYQHiker4klg0228","name": "🔨原盘4k1","type": 3,"api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./中国蓝光网.json","jar": "./spider (77).jar;md5;1A00D5032CC02FAD54510BAB6D48ED4A"},
{"key":"喵次元","name":"☣️喵次元","type":3,"api":"./drpy2.min.js","ext":"./喵次元.js"},
{"key":"达达龟_30208","name":"📻达达龟","type":"3","api":"./drpy2.min.js","ext":"./达达龟.js"},
{"key":"88看球_30215","name":"📻88看球","type":"3","api":"./drpy2.min.js","ext":"./88看球.js"},
{"key":"秒播短剧04","name":"秒播短剧","type":3,"api":"csp_Wexduanjuvop","searchable":1,"changeable":1,"jar": "https://ghproxy.net/https://raw.githubusercontent.com/PizazzGY/TVBox/main/spider.jar;md5;1ee361a1e82bb47bb7a9582055634ca3"},
{"key":"极品短剧04","name":"极品短剧","type":3,"api":"csp_Wexduanjuvmp","searchable":1,"changeable":1,"jar": "https://ghproxy.net/https://raw.githubusercontent.com/PizazzGY/TVBox/main/spider.jar;md5;1ee361a1e82bb47bb7a9582055634ca3"},
{"key":"88球迷0218","name":"⛹️⚽88球迷","type":3,"api":"csp_Kanqiu","jar": "./Yoursmile9BE.jar;md5;968B226E17CAF498DB6B89473B76D9BE"},
{"key": "JustLive","name": "JustLive","type": 3,"api": "csp_JustLive","searchable": 1,"changeable": 0,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "Xunlei0118","name": "🧲迅雷8","type": 3,"api": "csp_Xunlei8","playerType": 1,"searchable": 1,"quickSearch": 1,"filterable": 1,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "新6V","name": "🧲新6V","type": 3,"api": "csp_Xb6v","searchable": 1,"changeable": 1,"timeout": 60,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "酷狗0118","name": "🎵酷狗","type": 3,"api": "csp_Kugou","searchable": 1,"changeable": 0,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key":"ktv_open2","name":"🐳Iktv","type":3,"api":"./ktv_open.js"},
{"key":"yinyuetai_open2","name":"🐳🛰音悦台","type":3,"api":"./yinyuetai_open.js"},
{"key":"liumingye_open2","name":"🐳liumingye","type":3,"playerType":"1","api":"./liumingye_music_open.js"},
{"key":"T4_A8音乐","name":"🎙️A8音乐(T4)","type":4,"api":"https://catbox.n13.club/t4/a8.php","searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":true},
{"key": "4kys_open","name": "🐳4K影视","type": 3,"api": "./4kys_open.js"},
{"key": "subaibai_open","name": "🐳subaibai","type": 3,"api": "./subaibai_open.js"},
{"key": "csp_Hiker_DJ呦呦音乐网","name": "🎺 DJ呦呦音乐 ","type": 3,"jar": "https://d.kstore.space/download/2960/jar/XYQ.txt;md5;43485bc25714193e43f131def06329d9","api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,
"ext": "https://d.kstore.space/download/2960/js/DJ呦呦音乐网.json"},
{"key": "七夜0118","name": "💮七夜pg","type": 3,"api": "csp_Dovx","playerType":1,"searchable": 1,"quickSearch": 1,"filterable": 0,"changeable": 0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+auto|4k|fhd","jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key":"csp_WoGG","name":"👽玩偶哥哥","type":3,"api":"csp_WoGG","searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd$$$https://www.wogg.xyz/$$$弹","jar": "./Yoursmile.jar"},
{"key":"YiSo","name":"🆎易搜","type":3,"api":"csp_YiSo","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"PanSou","name":"📀盘搜","type":3,"api":"csp_PanSou","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"UpYun","name":"☁️UP云搜","type":3,"api":"csp_UpYun","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"PanSearch","name":"🙀盘搜索","type":3,"api":"csp_PanSearch","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"Dovx","name":"😾七夜","type":3,"api":"csp_Dovx","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"csp_QuarkPanso","name":"🐺夸搜","type":3,"api":"csp_QuarkPanso","searchable":1,"quickSearch":1,"changeable":0,"ext":"http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"push_agent","name":"🍭推送","type":3,"api":"csp_Push","searchable":0,"quickSearch":0,"filterable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt---4k|auto|fhd","jar": "./Yoursmile.jar"},
{"key":"三六零弹幕0320","name":"三六零弹幕一","type":3,"api":"csp_Sp360","searchable":1,"filterable":1,"changeable":1,"ext":{"danmu":true},"jar":"./danmu (0403).jar;md5;FC1C5BCDB0D48444DC1C08E4E300A9D4"},
{"key": "短剧0305","name": "短剧","type": 3,"api": "csp_Duanju","searchable": 0,"changeable": 1,"ext":"https://www.duanjutv.icu","jar": "https://agit.ai/xxpctv/m/raw/branch/master/py/pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "櫻花0305","name": "櫻花","type": 3,"api": "csp_Ying","searchable": 1,"changeable": 0,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "巴士0305","name": "巴士","type": 3,"api": "csp_Dm84","searchable": 1,"changeable": 0,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "異界0305","name": "異界","type": 3,"api": "csp_Ysj","searchable": 1,"changeable": 0,"jar": "./pg (0305).jar;md5;9658EEB13CCD1C3A4974FE8EBEF23DF2"},
{"key": "dr_drpy_bilizhoujck","name": "🅱哔站纪录片","type": 3,"api": "./drpy2.min.js","searchable": 0,"ext": "./doc.js"},
{"key":"csp_Bilizhoujck","name":"🅱哔站学习","type":3,"api":"csp_Bili","searchable":0,"changeable":0,"ext":"./bilibili.json"},

{"key": "荐片2","name": "Ⓜ️荐片js","type": 3,"api": "./drpy2.min.js","playerType":"1","searchable": 1,"changeable": 1,"ext":"./荐片.js"},
{"key":"csp_JianPian1224","name":"🔨荐片","type":3,"api":"csp_JianPian","playerType":1,"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://ownjpykxttjzuhy.jiesiwa.com","jar":"https://jihulab.com/clear1/yingmi/-/raw/main/jar/custom_spider.jar;md5;355a6227d33a26924bdbd795ae58955f"},
{"key": "csp_XYQHiker4klg","name": "🔨原盘4k","type": 3,"api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://jihulab.com/ymz1231/json/-/raw/main/%E4%B8%AD%E5%9B%BD%E8%93%9D%E5%85%89%E7%BD%91.json","jar":"./xyqxbpq.jar;md5;FD3CEFC7302F3A39A442682F802B11E5"},
{"key":"业余","name":"业余","type": 1,"api": "http://ys.540734621.xyz/api.php/provide/vod/","playerType": 1,"searchable": 1,"quickSearch": 1,"filterable": 1,"categories": ["短剧","电影","电视剧","动漫","综艺","记录片","音乐","影视解说","体育"]},
{ "key":"drpy_js_南瓜影视1203", "name":"🎃南瓜", "type":3, "api":"https://xhdwc.tk/lib/drpy2.min.js", "ext":"https://xhdwc.tk/js/南瓜影视.js" },
{"key": "csp_xml_ikun","name": "🈴ikun","type": 1,"api": "https://ikunzyapi.com/api.php/provide/vod/from/ikm3u8/at/json","searchable": 1,"playUrl": "https://www.ikdmjx.com/?url=","quickSearch": 1,"filterable": 1,"playerType": 2,"categories": ["动作片","喜剧片","科幻片","恐怖片","爱情片","剧情片","战争片","记录片","国产剧","欧美剧","犯罪片","惊悚片","古装片","灾难片","历史片","香港剧","韩国剧","台湾剧","日本剧","海外剧","泰国剧","其他片","悬疑片","奇幻片","动画片","国产动漫","日韩动漫","欧美动漫","大陆综艺","港台综艺","日韩综艺","欧美综艺"]},
{"key": "火狐0114","name": "🦊豪华资源","type": 1,"api": "https://hhzyapi.com/api.php/provide/vod/","searchable": 1,"quickSearch": 0,"filterable": 1,"categories": ["内地剧","短剧","动作片","科幻片","战争片","喜剧片","爱情片","恐怖片","犯罪片","剧情片","冒险片","记录片","韩剧","香港剧","台湾剧","欧美剧","日剧","马泰剧","体育赛事","综艺","动画片","中国动漫","日本动漫","欧美动漫"]},
{"key":"鲸落","name":"💢鲸落","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":{"主页url":"http://www.tvyb03.com/","请求头":"手机","简介":"class=\"sketch content\">&&</span>","数组":"myui-vodlist__thumb&&</a>","标题":"title=\"&&\"","副标题":"pic-tag pic-tag-top\">&&</span>","图片":"data-original=\"&&\"","链接":"href=\"&&\"","搜索url":"/vod/search.html?wd={wd}&submit=","搜索数组":"myui-vodlist__thumb&&</a>","搜索标题":"title=\"&&\"","搜索副标题":"pic-tag pic-tag-top\">&&</span>","搜索图片":"http://w.g9.pub:66/f/Y1ksA/sorry.ico","搜索链接":"href=\"&&\"","搜索模式":"1","嗅探词":".m3u8#.mp4#video_mp4#feiyunNB.mp4#.mp4#cdn.123pan.cn#huoshanvod.com#v.123pan.cn#auth_key#app-ali-cdn.fqfilm.com","搜索后缀":"/vod/detail/id/","线路数组":"</a><h3&&/h3>","线路标题":"title\">&&<","播放数组":"<ul class=\"myui-content__list scrollbar&&</ul>","播放标题":">&&<","播放列表":"<a&&/a>","分类url":"http://www.tvyb03.com/vod/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/page/{catePg}/year/{year}.html;;m","分类":"电影$1#电视剧$2#综艺$3#动漫$4"}},
{"key":"量子","name":"🍓量子资源","type":0,"api":"https://cj.lziapi.com/api.php/provide/vod/at/xml/","searchable":1,"changeable":1,"categories":["国产剧","香港剧","韩国剧","日本剧","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","欧美剧","记录片","海外剧","泰国剧","大陆综艺","港台综艺","日韩综艺","欧美综艺","欧美动漫","港台动漫","海外动漫","国产动漫","日韩动漫","体育","足球","篮球","网球","斯诺克"]},

{"key": "cntv2","name": "🍥央视open2","type": 3,"api": "./cntv2_open.js","searchable": 1,"changeable": 1},
{"key":"kanqiu_open","name":"体育看球open","type":3,"api":"./kanqiu_open.js"},
{"key": "nkvod_open0220","name": "耐看open","type": 3,"api": "./nkvod_open.js"},

{"key":"drpy_js_xb6v1203","name":"新6V","type":3,"api":"https://xhdwc.tk/lib/drpy2.min.js","ext":"./xb6v.js","playerType":"1", "searchable":1, "quickSearch":1, "changeable":1, "timeout":30},
 {"key":"电影港1203","name":"电影港js","type":3,"api":"https://xhdwc.tk/lib/drpy2.min.js","ext":"./dygang.js","playerType":"1", "searchable":1, "quickSearch":1, "changeable":0, "timeout":30},

{"key": "XBPQ_6V","name": "🧲6V4K磁力","type": 3,"api": "csp_XBPQ",
"ext": {"分类url":"https://www.66ss.org/{cateId}/index_{catePg}.html[https://www.66ss.org/{cateId}]","分类":"喜剧片4K$xijupian#动作片4K$dongzuopian#爱情片4K$aiqingpian#科幻片4K$kehuanpian#恐怖片4K$kongbupian#剧情片4K$juqingpian#战争片4K$zhanzhengpian#纪录片4K$jilupian#动画片4K$donghuapian#电视剧4K$dianshiju#综艺4K$ZongYi"  }},
{"key": "csp_XBPQ_mp4cl","name": "mp4cl","type": 3,"api": "csp_XBPQ","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./mp4cl.json"},
{"key": "csp_XBPQ_ 970417","name": "电影港","type": 3,"api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "/电影港.json"},
{"key":"py_cctv","name":"🌏爱央视（PY)","type":3,"api":"py_cctv","searchable":0,"quickSearch":0,"filterable":1,"ext":"./py_cctv.py"},
{"key": "py_cctv","name": "🇨🇳CCTV大全(PY)","type": 3,"api": "py_cctv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "./py_cctv2.py"},
{"key": "py_央视片库","name": "央视片库(PY)","type": 3,"api": "py_cctv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "./央视片库.py"},
{"key": "py_cctv_6","name": "🇨🇳CCTV(PY可搜索)","type": 3,"api": "py_cctv","searchable": 1,"quickSearch": 0,"filterable": 0,"ext": "./py_cctv.py"},
{"key": "py_bilimd","name": "B站影视(PY)","type": 3,"api": "py_bilimd","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./py_bilimd.py"},
{"key":"py_bilibili3","name":"B 站(PY)","type":3,"api":"py_bili","style":{ "type":"rect", "ratio":1.33 },"searchable":1,"quickSearch":1,"filterable":1,"ext":"./py_bilibili3.py"},
{"key":"py_1905","name":"🌏1905（PY)","type":3,"api":"py_cctv","searchable":0,"quickSearch":0,"filterable":1,"ext":"./py_1905.py"},
{"key": "py_kt30","name": "🐈卡通站(PY)","type": 3,"api": "py_kt30","searchable": 1,"quickSearch": 0,"filterable": 0,"ext": "htt./py_kt30.py"},
{"key": "py_gaoqing","name": "🐯高清资源(PY,绿化)","type": 3,"api": "py_gaoqing","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "./高清资源.py"},
{"key": "py_xinl","name": "🥡新浪资源(PY,绿化)","type": 3,"api": "py_xinl","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "./新浪资源.py"},
{"key": "drjs_bili","name": "哔站纪录片","type": 3,"api": "./drpy2.min.js","searchable": 1,"changeable": 1,"quickSearch": 0,"filterable": 1,"ext": "./哔站纪录片.js"},
{"key": "MTV转点播","name": "🎶16万MV","type": 3,"api": "http://152.32.170.60/66666/mv/raw/branch/master/live_min.js","ext": "http://152.32.170.60/66666/mv/raw/branch/master/live_min.txt"},
{"key":"爱听音乐网0206","name":"📻爱听音乐网","type":"3","api":"./drpy2.min.js","ext":"./爱听音乐网.js"},
{"key":"csp_YQKAPP","name":"🌎一起看","type":3,"api":"csp_YQKAPP","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"ext":"./YoursmileED3.jar;md5;9C583833C9809E13D924E3A2E27A2ED3"},
{"key": "dr_低端","name": "低端js","type": 3,"api": "./drpy2.min.js","playerType":2,"searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://xhdwc.tk/js/ddys.js"},
{"key":"drpy_js骚火电影","name":"骚火电影[js]","type":3,"api":"https://xhdwc.tk/lib/drpy2.min.js","ext":"https://xhdwc.tk/js/骚火电影.js"},
{"key":"dr_快看","name":"🎈快看js","type":3,"api": "./drpy2.min.js","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "./快看.js"},
{"key":"快看","name":"🚴快看","type":3,"api":"csp_Kuaikan","searchable":1,"quickSearch":1,"filterable":1},
{"key": "drpy_js_360影视","name": "💘360(d)","type": 3,"api": "./drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext": "./360影视.js"},
{"key":"drpy_小Q","name":"QQ(d)","type":3,"api":"./drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"./腾云.js"},
{"key":"drpy_忙果","name":"芒果(d)","type":3,"api":"./drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"./百忙无果.js"},
{"key":"drpy_爱奇艺","name":"爱奇艺(d)","type":3,"api":"./drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"./奇珍异兽.js"},
{"key":"drpy_U酷","name":"优酷js","type":3,"api":"./drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"./优酷.js"},
{"key":"优直播1220","name":"⛹️优直播✨","type":3,"playerType":1,"api":"./drpy.min.js","ext":"./优直播.js"},
{"key":"dr_直播迷129","name":"⛹️直播迷✨","type":3,"api":"./drpy.min.js","ext":"./直播迷.js"},
{"key":"csp_Bttoo","name":"✌两个BT","type":3,"api":"csp_Bttwoo","searchable":1,"quickSearch":1,"filterable":1,"jar":"./YoursmileED3.jar;md5;9C583833C9809E13D924E3A2E27A2ED3"},
{"key":"csp_Qtv","name":"🐧腾讯(d)","type": 3,"api":"csp_Qtv","searchable": 1,"quickSearch": 1,"filterable":1,"changeable":0},
{"key":"csp_Itv","name":"🥝爱奇艺(d)","type":3,"api":"csp_Itv","quickSearch":1,"searchable":1,"filterable":1,"changeable":0},
{"key":"csp_Mtv","name":"🍋芒果(d)","type":3,"api":"csp_Mtv","searchable":1,"quickSearch":1,"filterable":1,"changeable":0},
{"key":"Aid","name":"🚑急救教学","type":3,"api":"csp_FirstAid","searchable":0,"quickSearch":0,"filterable":0,"changeable":0},
{"key":"csp_Mayiys","name":"🐜蚂蚁","type":3,"api":"csp_Mayiys","searchable":1,"quickSearch":1,"filterable":0,"ext":"http://rzys.xyz"},
{ "key": "ff","name": "🌱非凡","type": 1,"api": "http://cj.ffzyapi.com/api.php/provide/vod/","playUrl": "","searchable": 1,"quickSearch": 1,"filterable": 1,"categories": ["国产剧"]},
{"key":"csp_XBPQ_骚火影视","name":"️☀️骚火影视","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":0,"ext":"./骚火影视.json"},
{"key": "csp_XYQBiu_TVB云播","name": "🌱TVB云播","type": 3,"api": "csp_XYQBiu","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./TVB云播.json"},
{"key":"dr_JRKAN直播","name":"⚡直播赛事","type":3,"playerType":1,"api":"./drpy.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"./JRKAN.js"},
{"key":"JRKAN2","name":"⛹️直播赛事2","type":3,"playerType":1,"api":"./drpy.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"./JRKANvs.js"},
{"key":"虎牙","name":"🐯虎牙","type":1,"api":"https://www.huyaapi.com/api.php/provide/vod/from/hym3u8","searchable":1,"quickSearch":1,"categories":["内地剧","动作片","科幻片","战争片","喜剧片","爱情片","恐怖片","犯罪片","剧情片","冒险片","记录片","韩剧","香港剧","台湾剧","欧美剧","日剧","马泰剧","体育赛事","综艺","动画片","中国动漫","日本动漫","欧美动漫"]},
{"key":"dr_兔小贝","name":"🐰兔小贝","type":3,"api":"./drpy2.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"./兔小贝.js"},
{"key":"csp_XYQHiker_兔小贝2","name":"🐰兔小贝❷","type":3,"api":"csp_XYQHiker","searchable":1,"quickSearch":1,"filterable":1,"ext":"./兔小贝2.json"},
{"key":"1080","name":"1080p","type":1,"api":"https://api.1080zyku.com/inc/api_mac10.php","searchable":0,"quickSearch":0,"categories":["国产剧","综艺","动漫","动画片","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","韩国剧","欧美剧","香港剧","泰国剧","日本剧","港台剧"]},
{"key":"U酷资源","name":"U酷","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["综艺","动漫","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","国产剧","港澳剧","日剧","欧美剧","动漫电影","台湾剧","韩剧","泰剧","记录片"]},
{"key": "老年人频道","name": "⚡粤剧","type": 3,"api": "csp_Bili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "./yueju.json"},
{"key":"csp_Bili合集","name":"🌎综艺up","type": 3,"api": "csp_Bili","searchable":1,"quickSearch":1,"filterable":1,"ext":"./Biliup.json"},
{"key":"csp_AppMr","name":"👻明明影视","type":3,"api":"csp_AppMr","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_xp_qiumi","name":"✌球迷","type":3,"api":"csp_XPath","playerType":1,"searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/py_qm.py"},
{"key":"csp_Voflix","name":"🌀Voflix","type":3,"api":"csp_Voflix","searchable":1,"quickSearch":1,"filterable":1},
{"key":"纪录","name":"✨纪录","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./纪录片.json"},
{"key": "赛车","name": "🚗赛车","type": 3,"api": "csp_Bili","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./yueye.json"},
{"key":"csp_Anime1","name":"🌸动漫","type":3,"api":"csp_Anime1","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Dm84","name":"🚌动漫巴士","type":3,"api":"csp_Dm84","searchable":1,"quickSearch":1,"filterable":1},
{"key":"push_agent2","name":"🍭推送","type":3,"api":"csp_Push","searchable":0,"quickSearch":0,"filterable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key":"csp_AList","name":"🅰AList网盘","type":3,"api":"csp_AList","searchable":1,"quickSearch":0,"filterable":1,"changeable":0,"ext":"./alist_xm.json"},
{"key":"drpy_js_六月听书","name":"💧六月听书","type":3,"api":"./drpy2.min.js","ext":"./六月听书.js","playerType":"2"},
{"key":"csp_XBPQ_非凡资源","name":"💢非凡","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":"./非凡资源.json"},
{"key":"csp_XBPQ_量子资源","name":"💢量子","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":"./量子资源.json"},
{"key":"csp_XBPQ_奇优","name":"️💢奇优","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":"./奇优.json"},
{"key": "黑狐","name": "🦊黑狐XB","type": 3,"searchable": 1,"quickSearch": 1,"playerType": "1","api": "csp_XBPQ","ext": {"站名":"黑狐影院","主页url":"http://fagmn.com","数组":"class=\"stui-vodlist__box\"&&</a","图片":"data-original=\"&&\"","标题":"title=\"&&\"","链接":"href=\"&&\"","嗅探词":".m3u8#v3.huoshanvod.com#v3-dy-o.zjcdn#sf16-sg.larksuitecdn.com#v.kd1.qq.com","过滤词":"/hls/#php","副标题":"<span class=\"pic-text text-right\">&&</span>","搜索url":"http://fagmn.com/search.php;post;searchword={wd}","搜索模式":"1","搜索数组":"<a class=\"v-thumb stui-vodlist__thumb&&</a>","搜索图片":"data-original=\"&&\"","搜索标题":"title=\"&&\"","搜索链接":"href=\"&&\"","搜索副标题":"<span class=\"pic-text text-right\">&&</span>","搜索后缀":"/view/","线路数组":"href=\"#down&&/a>[替换:奇异视频>>黑狐一线#优酷视频>>黑狐二线#搜狐视频>>黑狐三线#咪咕视频>>黑狐四线]","线路标题":">&&<","播放数组":"class=\"stui-content__playlist clearfix&&</ul>","状态":"地区：&&</p>","导演":"导演：&&</p>","主演":"主演：&&</p>","简介":"简介：&&</div>","播放列表":"<a&&/a>","播放标题":">&&<","播放链接":"href=\"&&\"","免嗅":"0","分类":"电影$1#电视剧$2#动漫$3#综艺$4","分类url":"http://fagmn.com/list/{cateId}_{catePg}.html?order=time"}},
{"key":"JRKAN直播","name":"JRKAN直播","type":3,"playerType":1,"api":"./drpy.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"./JRKAN直播.js"},
{"key":"dr_虎牙","name":"🐯虎牙","type":3,"api":"./drpy2.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"./虎牙直播.js"},

{"key": "csp_XYQBiu_斗鱼","name": "🐟斗鱼直播","type": 3,"api": "./drpy.min.js","ext": "./斗鱼直播.js","searchable": 0,"quickSearch": 0,"changeable": 0},
{"key": "csp_XYQHiker_兔小贝","name":"兔小贝(XYQH)","type":3,"api":"csp_XYQHiker","searchable":1,"quickSearch":1,"filterable":1,"ext":"./兔小贝2.json"},

{"key":"蜻蜓FM1223","name":"🚦蜻蜓FM🚦","type":3,"api":"./drpy2.min.js","changeable":0,"ext":"https://ghproxy.net/https://raw.githubusercontent.com/xxpctv/dr_py/main/js/%E8%9C%BB%E8%9C%93FM.js"},
{"key": "酷奇js","name": "🎤酷奇┃MV","type": 3,"api": "./drpy2.min.js","ext": "./酷奇MV.js","style": {"type": "rect","ratio": 1.597},"searchable": 0,"quickSearch": 0,"changeable": 0},
{"key":"csp_xpath_A33","name":"🎸MTV","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":1,"ext":"http://home.jundie.top:81/TVBox/MaooXB/mtv.json"},
{"key": "哔哩DL0303","name": "锻炼身体","type": 3,"api": "csp_Bili","searchable": 0,"quickSearch": 0,"filterable": 0,"ext": "./锻炼身体.json"},
{"key":"B站","name":"🅱B站","type":3,"api":"csp_Bili","ext":"./bz.json"},
{"key":"美食","name":"哔哔合集","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":0,"ext":"./bilibili.json"},
{"key":"csp_Biliych","name":"哔哔演唱会","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./biliych.json"},
{"key":"drpy_blzb","name":"🅱️哔哩zb","type":3,"api":"./drpy2.min.js","ext":"./哔哩直播.js"},
{"key": "csp_Bliyc学前","name": "🅱️学前教育(SP)","type": 3,"api": "csp_Bili","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "./学前儿童.txt"},
{"key":"csp_Bili","name":"🅱️哔哩哔哩","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./Bili.json"},
{"key":"相声小品","name":"🅱️相声小品","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./Blixs.json"},
{"key":"戏曲","name":"🅱️戏曲","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./Blixq.json"},
{"key":"少儿","name":"🅱️少儿","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./少儿教育.json"},
{"key":"小学","name":"🅱️小学","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./小学课堂.json"},
{"key":"初中","name":"🅱️初中","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./初中课堂.json"},
{"key":"高中","name":"🅱️高中","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"./高中课堂.json"}],
"parses": [
{"name":"智能解析","type":2,"url": "Sequence"},
{
		"name": "Web聚合",
		"type": 3,
		"url": "Web"
	},
{
		"name": "Json聚合",
		"type": 3,
		"url": "Demo"
	},
{"name": "84jia","type": 1,"url": "http://json.84jia.com/home/api?type=ys&uid=335253&key=demprsyzBMQRVY0234&url="},	
{"name": "NG解析","type": 1,"url": "http://119.91.123.253:2345/Api/yun.php?url="},
{"name": "超聚合1", "type": 1, "url": "http://xiutan.shiyifacai.com/json/qingfeng.php?url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header": {"User-Agent": "Lavf/58.12.100"}}},  	
{"name": "超解2", "type": 1, "url": "http://122.228.84.103:7777/api/?key=TJ5aojxggobuP4CTTw&url=","ext":{"flag":["SMD","Feiyun","NBY","qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header": {"User-Agent":"Dart/2.18 (dart:io)"}}},  	
{"name":"PM","url":"https://www.playm3u8.cn/jiexi.php?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},	
{"name":"线路1","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
	{"name":"线路2","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
	{"name":"线路3","type":0,"url":"https://jx.quankan.app/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
	{"name":"线路4","type":0,"url":"https://jx.yparse.com/index.php?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
	{"name":"线路5","type":0,"url":"https://jx.jsonplayer.com/player/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
	{"name":"线路6","type":0,"url":"https://jx.xyflv.cc/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36","referer":"https://www.xyflv.cc/"}}},
	{"name":"线路7","type":0,"url":"https://jx.aidouer.net/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36","referer":"https://jiejie.uk/"}}},
	{"name":"线路8","type":0,"url":"https://jx.zhanlangbu.com/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}}},
	{"name":"线路9","type":0,"url":"https://jx.777jiexi.com/player/?url="},
	{"name":"线路10","type":0,"url":"https://www.8090g.cn/?url="},
	{"name":"线路11","type":0,"url":"https://jx.yangtu.top?url="},
	{"name":"线路12","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},	
	{"name":"线路13","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name":"不累","type":0,"url":"https://blbfq.f3322.net/player/analysis.php?v=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"cod","type":0,"url":"https://ksksl.codjx.com/?url="},
{"name":"byg解析","type":0,"url":"https://byg.ziqj5.shop/?url="},
{"name":"xmflv","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"365","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"26db","type":0,"url":"http://vip.26db.cn/g/?url="},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"FreeOK","type":0,"url":"https://play.86516.tk/OKPlayer/?url="},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url="},
	 
{"name":"弹幕解析","type":0,"url":"https://jiexi.555jiexi.net:555/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜","1905","ltnb","renrenmi","rx","rongxing"]}},	
{"name":"夜幕","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"-虾米-","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
{"name":"-云解析-","type":0,"url":"https://jx.yparse.com/index.php?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name":"-777-","type":0,"url":"https://jx.jsonplayer.com/player/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name":"-全看-","type":0,"url":"https://jx.quankan.app/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name":"-爱豆-","type":0,"url":"https://jx.aidouer.net/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36","referer":"https://jiejie.uk/"}}},
{"name":"-咸鱼-","type":0,"url":"https://jx.xyflv.cc/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36","referer":"https://www.xyflv.cc/"}}},	
{"name": "解析1","type": 1,"url": "http://61.147.93.21:8090/index.php?url="},
{"name":"线路2","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
	{"name": "g9","type": 1,"url": "http://json.g9.pub:66/?url=","ext": {"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}}, 
{"name":"ckmov","type":0,"url":"https://yun.ckmov.com/?url="},
{"name":"🎯分享有爱","type":1,"url":"https://svip.cygc.xyz/api/?key=dVtcmaBX6lt954hcKJ&url="},
{"name":"💕推荐","type":1,"url":"http://42.157.129.144:2323/CH/caihong_1993138546.php?url="},
{"name": "分享智能","type": 1,"url": "http://json.84jia.com/home/api?type=ys&uid=335253&key=acefhmqsxEMPRVYZ26&url="},
{"name": "分享智能1","type": 1,"url": "http://119.91.123.253:2345/Api/yun.php?url="},
{"name": "分享自动","type":1,"url":"http://42.157.129.144:2323/CH/caihong_1993138546.php?url="},

{"name":"推荐💕","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"默认💕","url": "https://vip.lianfaka.com/vip/?url=","ext":{"header": 
 {"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1","Referer": "https://www.dy6g.com/"}}},
 {"name": "超解析", "type": 1, "url": "http://110.42.2.247:880/analysis/json/?uid=2384&my=bcijquvxAFKMUY0579&format=json&url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},  
{"name": "超聚合", "type": 1, "url": "http://110.42.2.247:880/analysis/json/?uid=2255&my=eimqrtwxBCDIKT2458&format=json&url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},
{"name":"高清解析1","type":1,"url":"https://vip.xuux.icu/home/api?type=ys&uid=1325731&key=adfgilmnpwzBDEJPY3&url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},

{"name":"综合/B站/", "type":0,"url":"https://jx.jsonplayer.com/player/?url=", "showType":3},
 {"name": "777","type": 0,"url": "https://jx.777jiexi.com/player/?url="},
    {"name": "ok","type": 0,"url": "http://okjx.cc/?url="},
    {"name": "yp","type": 0,"url": "https://jx.yparse.com/index.php?url="},
    {"name": "boz","type": 0,"url": "https://jx.bozrc.com:4433/player/?url="},
    {"name": "aid","type": 0,"url": "https://jx.aidouer.net/?url="},
 {"name": "json","type": 0,"url": "https://jx.jsonplayer.com/player/?url="},
  {"name": "dyg","type": 0,"url": "http://hangup.tk:5705/parse/api/dyg.js?url="},
{"name": "芒果","type": 1,"url": "http://110.42.2.247:880/analysis/json/?uid=2255&my=bcdkloqxzEFGPRT168&format=json&url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header": {"User-Agent": "okhttp/4.1.0"}}}, 
{
		"name": "刚佬",
		"type": 1,
		"url": "http://json.g9.pub:66/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		} 
	}, {
		"name": "未知",
		"type": 1,
		"url": "https://vip.mosangkeji.com/api/?key=rRNvXAnOghBBLnC35c&url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"]
		} 
	}, {
		"name": "777",
		"type": 0,
		"url": "https://jx.777jiexi.com/player/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}   
	}, {
		"name": "bozrc",
		"type": 0,
		"url": "https://jx.bozrc.com:4433/player/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}   
	}, {
		"name": "zhanglang",
		"type": 0,
		"url": "https://jx.zhanlangbu.com/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}    
	}, {
		"name": "左岸",
		"type": 0,
		"url": "https://jx.jsonplayer.com/player/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}   
	}, {
		"name": "ckmov",
		"type": 0,
		"url": "https://yun.ckmov.com/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"]
		}  
	}],
"lives": [{"group": "redirect","channels": [{"name": "live","urls": ["proxy://do=live&type=txt&ext=aHR0cHM6Ly9ub3RhYnVnLm9yZy94eHBjdHYvZHovcmF3L21hc3Rlci9qYXIvZHMudHh0"]}]}],
"doh":[{"name":"Google","url":"https://dns.google/dns-query","ips":["8.8.4.4","8.8.8.8"]},{"name":"Cloudflare","url":"https://cloudflare-dns.com/dns-query","ips":["1.1.1.1","1.0.0.1","2606:4700:4700::1111","2606:4700:4700::1001"]},{"name":"AdGuard","url":"https://dns.adguard.com/dns-query","ips":["94.140.14.140","94.140.14.141"]},{"name":"DNSWatch","url":"https://resolver2.dns.watch/dns-query","ips":["84.200.69.80","84.200.70.40"]},{"name":"Quad9","url":"https://dns.quad9.net/dns-quer","ips":["9.9.9.9","149.112.112.112"]}],
   "warningText": "有事做有所期待，日子就是幸福的。", 
   "rules":[
{"name": "proxy","hosts": ["raw.githubusercontent.com","googlevideo.com","cdn.v82u1l.com","cdn.iz8qkg.com","cdn.kin6c1.com","c.biggggg.com","c.olddddd.com","haiwaikan.com","www.histar.tv","youtube.com","uhibo.com",".*boku.*",".*nivod.*","*.t4tv.hz.cz",".*ulivetv.*"]},
{"name": "量子","hosts": ["vip.lz","hd.lz","v.cdnlz"],"regex": ["18.5333"]},
{"name":"量子广告","hosts":["vip.lz","hd.lz","v.cdnlz1","v.cdnlz"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.433333,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},
{"name":"非凡广告","hosts":["vip.ffzy","hd.ffzy"],"regex":["25.0666","#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.666667,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},
{"name": "非凡","hosts": ["vip.ffzy","hd.ffzy"],"regex": ["25.0666","25.08"]},
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]},
{"name":"索尼广告","hosts":["suonizy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:7.680000,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},
{"name":"暴风广告","hosts":["bfzy","s5.bfzycdn"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},
{"name": "夜市","hosts": ["yeslivetv.com"],"script": ["document.getElementsByClassName('vjs-big-play-button')[0].click()"]},
{"name": "毛驢","hosts": ["www.maolvys.com"],"script": ["document.getElementsByClassName('swal-button swal-button--confirm')[0].click()"]},
{"name":"火山嗅探","hosts":["huoshan.com"],"regex":["item_id="]},
{"name":"抖音嗅探","hosts":["douyin.com"],"regex":["is_play_url="]},
{"name":"快看广告","hosts":["kuaikan"],"regex":["#EXT-X-KEY:METHOD=NONE\\r*\\n*#EXTINF:5,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXT-X-KEY:METHOD=NONE\\r*\\n*#EXTINF:2\\.4,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},
{"name":"极速广告","hosts":["jszy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*[\\s\\S]*?#EXT-X-DISCONTINUITY"]},
{"name":"磁力广告","hosts":["magnet"],"regex":["更多","请访问","example","社 區","x u u","直 播","更 新","社 区","有趣","有 趣","英皇体育","全中文AV在线","澳门皇冠赌场","哥哥快来","美女荷官","裸聊","新片首发","UUE29"]},
{"name":"wp","hosts":["vip.123pan.cn","rescdn.wuxivlog.cn"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:20.840000,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:10.120000,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},
{"name":"阳图","hosts":["jx.yangtu.top"],"regex":["download4.caiyun.feixin.10086.cn","/servlet/"]},
{"name":"廣告","hosts":["."],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.433333,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:8,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:7.680000,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.666667,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:15,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+","#EXTINF.*?\\s+.*?muguacdn.*?\\.ts\\s+"]},
{"name":"hwk","hosts":["haiwaikan"],"regex":["10.0099","10.3333","16.0599","8.1748","10.85"]},
{"name": "海外看","hosts": ["haiwaikan"],"regex": ["8.1748","10.0099","10.3333","16.0599"]},		    
{"name":"yqk","hosts":["yqk88"],"regex":["18.4","15.1666"]},
{"name":"sn","hosts":["suonizy"],"regex":["15.1666","15.2666"]},
{"name":"xx","hosts":["aws.ulivetv.net"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:8,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},
{"name":"lz","hosts":["vip.lz","hd.lz","v.cdnlz1","v.cdnlz"],"regex":["18.5333"]},
{"name":"nm","hosts":["toutiaovod.com"],"regex":["video/tos/cn"]}],
 "flags":["youku","qq","QQ","iqiyi","qiyi","letv","sohu","tudou","pptv","PPTV","mgtv","ltnb","rx","SLYS4k","BYGA","BYGB","luanzi","dxzy","QEYSS","aliyun","AliS","122","chuangying","CL4K","xfyun","wuduzy","wasu","bilibili","renrenmi","xmm","xigua","m1905","funshion","优酷","芒果","腾讯","爱奇艺","奇艺","哔哩哔哩","哔哩","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频","FY","fy","FeiYun","feiyun","飞云"],
   "ijk":[{"group":"软解码","options":[{"category":4,"name":"opensles","value":"0"},{"category":4,"name":"overlay-format","value":"842225234"},{"category":4,"name":"framedrop","value":"1"},{"category":4,"name":"soundtouch","value":"1"},{"category":4,"name":"start-on-prepared","value":"1"},{"category":1,"name":"http-detect-rangeupport","value":"0"},{"category":1,"name":"fflags","value":"fastseek"},{"category":2,"name":"skip_loop_filter","value":"48"},{"category":4,"name":"reconnect","value":"1"},{"category":4,"name":"enable-accurateeek","value":"0"},{"category":4,"name":"mediacodec","value":"0"},{"category":4,"name":"mediacodec-auto-rotate","value":"0"},{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"},{"category":4,"name":"mediacodec-hevc","value":"0"},{"category":1,"name":"dns_cache_timeout","value":"600000000"}]},{"group":"硬解码","options":[{"category":4,"name":"opensles","value":"0"},{"category":4,"name":"overlay-format","value":"842225234"},{"category":4,"name":"framedrop","value":"1"},{"category":4,"name":"soundtouch","value":"1"},{"category":4,"name":"start-on-prepared","value":"1"},{"category":1,"name":"http-detect-rangeupport","value":"0"},{"category":1,"name":"fflags","value":"fastseek"},{"category":2,"name":"skip_loop_filter","value":"48"},{"category":4,"name":"reconnect","value":"1"},{"category":4,"name":"enable-accurateeek","value":"0"},{"category":4,"name":"mediacodec","value":"1"},{"category":4,"name":"mediacodec-auto-rotate","value":"1"},{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"},{"category":4,"name":"mediacodec-hevc","value":"1"},{"category":1,"name":"dns_cache_timeout","value":"600000000"}]}],
   "ads":["iqiyi.hbuioo.com","vip.ffzyad.com","wan.51img1.com","https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd","mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"],"daily_sentence" : "https://v1.hitokoto.cn/?c=i&max_length=20"}

