{
	"spider": "https://agit.ai/xxpctv/m/raw/branch/master/py/YoursmileCCB.jar;md5;22EF4E19E3F1FA014DD8854D12DB9CCB",
	"wallpaper": "https://tuapi.eees.cc/api.php?category=fengjing&type=302",
"sites":[
{"key":"csp_DouDou","name":"🎧豆瓣┃评分","type":3,"api":"csp_DouDou","searchable":0,"quickSearch":0,"filterable":1},
{"key":"广播频道","name":"📡广播电台","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/py/live2mv.js","changeable":0,"ext":"广播电台$https://agit.ai/xxpctv/m/raw/branch/master/py/广播频道.txt"},
{"key":"豆瓣drpy","name":"🍬🍬豆瓣drpy","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=drpy"},
{"key": "tjbook","name": "🍬手机听书","type": 3,"api": "csp_Bili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/py/tjbook.json"},
{"key":"csp_Bttwoo1","name":"✌两个BT","type":3,"api":"csp_Bttwoo","searchable":1,"quickSearch":1,"filterable":1,"categories": ["最新","国产剧", "美剧","日韩剧"]},
{"key":"荐片1207","name":"荐片1207","type":3,"api":"csp_JianPian","playerType":1,"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://ownjpykxttjzuhy.jiesiwa.com","jar": "./Spider (jpxbpxyq).jar"},
{"key":"小小1214","name":"预告片","type":1,"api":"http://haowywz.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1,"categories":["预告片","国产剧"]},
{"key": "dr_drpy_bilizhoujck","name": "🅱哔站纪录片","type": 3,"api": "https://agit.ai/zhoujck/config/raw/branch/master/js/lib/drpy2.min.js","searchable": 0,"ext": "https://agit.ai/zhoujck/config/raw/branch/master/js/doc.js"},
{"key":"csp_Bilizhoujck","name":"🅱哔站学习","type":3,"api":"csp_Bili","searchable":0,"changeable":0,"ext":"https://agit.ai/zhoujck/config/raw/branch/master/ext/bilibili.json"},
{"key": "xh22","name": "🔥自营4k","type": 1,"playerType": 1,"api": "http://c.小胡.icu/api.php/provide/vod/","categories": ["电影","国产剧", "欧美剧","韩剧"]},
{"key":"荐片8","name":"☣️荐片(T4)","type":4,"api":"http://home.jundie.top:9520/spider/csp_JP","searchable":1,"quickSearch":1,"filterable":1},
{"key": "荐片2","name": "🚀荐片js","type": 3,"api": "https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","searchable": 1,"changeable": 1,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/dr/荐片.js"},
{"key":"dr_荐片","name":"荐片","type":3,"api":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/lib/drpy2.min.js","playerType":"1","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/荐片.js"},
{"key":"csp_JianPian1224","name":"🔨荐片","type":3,"api":"csp_JianPian","playerType":1,"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://ownjpykxttjzuhy.jiesiwa.com","jar":"https://jihulab.com/clear1/yingmi/-/raw/main/jar/custom_spider.jar;md5;355a6227d33a26924bdbd795ae58955f"},
{"key": "csp_XYQHiker4klg","name": "🔨原盘4k","type": 3,"api": "csp_XYQHiker","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://jihulab.com/ymz1231/json/-/raw/main/%E4%B8%AD%E5%9B%BD%E8%93%9D%E5%85%89%E7%BD%91.json","jar": "https://agit.ai/guot54/ygbh/raw/branch/master/JAR/spider.txt"},
{"key": "xh22","name": "🔥自营4k","type": 1,"playerType": 1,"api": "http://c.小胡.icu/api.php/provide/vod/"},
{"key":"九九六","name":"九九六","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":{"分类url": "https://www.cs1369.com/show/id/index.php/vod/show/area/{area}/id/{cateId}/page/{catePg}/year/{year}.html",
"分类": "电影$1#电视剧$2#动漫$3#爽文短剧$4#动作片$6#喜剧片$7#爱情片$8#科幻片$9#恐怖片$10#剧情片$11#战争片$12#动画片$13#纪录片$14","筛选": "1"}},
 {"key":"南瓜影视","name":"🎃南瓜🚦","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/南瓜影视.js"},
{"key":"南瓜","name":"🎃南瓜","type":3,"api":"csp_NanGua","jar":"https://agit.ai/xxpctv/m/raw/branch/master/py/fix0804.jar"},
{"key": "drpy_js_南瓜影视","name": "🎃南瓜dr","type": 3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","ext": "https://agit.ai/xyg2333/Box/raw/branch/master/js/%E5%8D%97%E7%93%9C.js"},
{ "key":"drpy_js_南瓜影视1203", "name":"🎃南瓜", "type":3, "api":"https://xhdwc.tk/lib/drpy2.min.js", "ext":"https://xhdwc.tk/js/南瓜影视.js" },
{"key": "NanGua1207","name": "🎃南瓜|弹幕pg","type": 3,"jar": "https://agit.ai/lirg/ocean/raw/branch/master/jars/pg.jar","api": "csp_NanGua","searchable": 1,"changeable": 1,"ext": "null$$$1"},
{"key": "天天开心自营","name": "🎦开心自营 ","type": 1,"api": "http://www.ttkx.site/api.php/provide/vod/","playerType": 2,"searchable": 1,"quickSearch": 1,"filterable": 1,"categories": ["动作片","战争片","国产剧","港台剧","日韩剧","欧美剧","国产动漫","日韩动漫","港台动漫","动画片","短剧","国产综艺","喜剧片","爱情片","科幻片","恐怖片","剧情片","灾难片","悬疑片","犯罪片","奇幻片","纪录片"]},
{"key":"zzdj","name":"🥑种子短剧","type":1,"api":"http://zzdj.cc/api.php/provide/vod"},
{"key":"XAL蓝光","name": "XAL蓝光","type":1,"api":"http://vipcom.xn--654a.cc/api.php/provide/vod/","playUrl":"json:http://json.xn--654a.cc/home/api?type=ys&uid=1323246&key=dfiopqzEHJKNOPSTY5&url=","searchable":1,"quickSearch":1},
{"key": "cntv","name": "视聚场open","type": 3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/py/cntv_open.js","searchable": 1,"changeable": 1},
{"key": "ng_open","name": "🎃_open","type": 3,"api": "https://agit.ai/kvymin/TV/raw/branch/master/catvod/ng_open.js","searchable": 1,"changeable": 1}, 
{"key":"荐片_7d1","name":"🍬荐片_7","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=%E8%8D%90%E7%89%87_7"},
{"key":"T6","name":"🍬2bt","type":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=%E4%B8%A4%E4%B8%AABT","searchable":1,"quickSearch":0,"filterable":1,"changeable":1},
{"key": "JRKANvs", "name": "🍬🍬JRKANvs", "type": 1,"playerType":1, "api": "https://xm.xxpctv.repl.co/vod?rule=JRKANvs"},
{"key": "六月听书", "name": "🍬🍬六月听书", "type": 1, "api": "https://xm.xxpctv.repl.co/vod?rule=%E5%85%AD%E6%9C%88%E5%90%AC%E4%B9%A6"},
{"key": "voflix2", "name": "🍬🍬voflix2", "type": 1, "api": "https://xm.xxpctv.repl.co/vod?rule=voflix2"},
{"key": "310直播2xm", "name": "🍬🍬310直播2", "type": 1,"playerType":1, "api": "https://xm.xxpctv.repl.co/vod?rule=310直播2"},
{"key": "速看100[V2]xm", "name": "🍬🍬速看100[V2]", "type": 1, "api": "https://xm.xxpctv.repl.co/vod?rule=速看100[V2]"},
{"key": "粤语古仔xm", "name": "🍬🍬粤语古仔xm", "type": 1, "api": "https://xm.xxpctv.repl.co/vod?rule=粤语古仔"},
{"key":"JRKAN直播_7xm","name":"🍬🍬JRKAN直播_7","type":1,"playerType":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=JRKAN直播_7"},
{"key":"drpy","name":"🍬🍬豆瓣drpy","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=drpy","searchable":1,"quickSearch":0,"filterable":1,"changeable":1},
{"key":"嘉靓tvxm","name":"🍬🍬嘉靓tv","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=dapeng"},
{"key":"369xm","name":"🍬🍬369","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=369"},
{"key":"Bttwoxm","name":"🍬🍬Bttwo","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=Bttwo"},
{"key":"9Uxm","name":"🍬🍬9U","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=9U"},
{"key":"直播迷_2xm","name":"🍬直播迷_2","type":1,"playerType":1,"api":"https://drpyxxpctv-1.xxpctv.repl.co/vod?rule=直播迷_2"},
{"key":"zizixm","name":"🍬🍬zizi","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=zizi"},
{"key":"新视觉xm","name":"🍬🍬新视觉","type":1,"api":"https://xm.xxpctv.repl.co/vod?rule=%E6%96%B0%E8%A7%86%E8%A7%89"},
{"key":"看球8xm","name":"🍬🍬看球8","type":1,"playerType":1,"api":"https://xm.xxpctv.repl.co/vod?rule=%E7%9C%8B%E7%90%838"},
{"key":"drpy_js_农民1227","name":"影视 | 农民[js]","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","ext":"https://agit.ai/xibao/YGBH22/raw/branch/main/js/农民影视.js"},
{"key":"dr_88看球","name":"88看球","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/88看球.js"},
{"key":"drpy_js_xb6v1203","name":"新6V","type":3,"api":"https://xhdwc.tk/lib/drpy2.min.js","ext":"https://agit.ai/boys180/cnmix/raw/branch/master/ext/xb6v.js","playerType":"1", "searchable":1, "quickSearch":1, "changeable":1, "timeout":30},
 {"key":"电影港1203","name":"电影港js","type":3,"api":"https://xhdwc.tk/lib/drpy2.min.js","ext":"https://agit.ai/boys180/cnmix/raw/branch/master/ext/dygang.js","playerType":"1", "searchable":1, "quickSearch":1, "changeable":0, "timeout":30},
{"key":"csp_WoGG","name":"👽玩偶哥哥","type":3,"api":"csp_WoGG","searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd+4k|auto|fhd"},
{"key":"YiSo","name":"🆎易搜","type":3,"api":"csp_YiSo","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key":"Zhaozy","name":"🦊找资源","type":3,"api":"csp_Zhaozy","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd$$$yingshi$$$abcd1234"},
{"key":"PanSou","name":"📀盘搜","type":3,"api":"csp_PanSou","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key":"UpYun","name":"☁️UP云搜","type":3,"api":"csp_UpYun","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key":"PanSearch","name":"🙀盘搜索","type":3,"api":"csp_PanSearch","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key":"Dovx","name":"😾七夜","type":3,"api":"csp_Dovx","searchable":1,"quickSearch":1,"filterable":0,"changeable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key": "七夜1213","name": "💮七夜","type": 3,"api": "csp_Dovx","searchable": 1,"quickSearch": 1,"filterable": 0,"changeable": 0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+auto|4k|fhd","jar": "https://agit.ai/xxpctv/m/raw/branch/master/py/Yoursmile1213.jar"},
{"key": "YiSo1213","name": "💮一搜","type": 3,"api": "csp_YiSo","searchable": 1,"quickSearch": 1,"filterable": 0,"changeable": 0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+auto|4k|fhd","jar": "https://agit.ai/xxpctv/m/raw/branch/master/py/Yoursmile1213.jar"},
{"key": "PanSearch1213","name": "💮盘搜","type": 3,"api": "csp_PanSearch","searchable": 1,"quickSearch": 1,"filterable": 0,"changeable": 0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+auto|4k|fhd","jar": "https://agit.ai/xxpctv/m/raw/branch/master/py/Yoursmile1213.jar"},
{"key": "csp_WoGG1213","name": "💮玩偶","type": 3,"api": "csp_WoGG","searchable": 1,"quickSearch": 1,"changeable": 0,"ext": "http://127.0.0.1:9978/file/tvfan/token.json+auto|4k|fhd$$$https://api.wogg.xyz/$$$弹","jar": "https://agit.ai/xxpctv/m/raw/branch/master/py/Yoursmile1213.jar"},
{"key":"玩偶哥哥","name":"👽玩偶已修复断流","type":3,"api":"csp_WoGG","searchable":1,"quickSearch":1,"changeable":0,"ext":"http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd$$$https://api.wogg.xyz/$$$弹","jar": "https://agit.ai/xxpctv/m/raw/branch/master/py/fty1213.jar"},
{"key": "XBPQ_6V","name": "🧲6V4K磁力","type": 3,"api": "csp_XBPQ",
"ext": {"分类url":"https://www.66ss.org/{cateId}/index_{catePg}.html[https://www.66ss.org/{cateId}]","分类":"喜剧片4K$xijupian#动作片4K$dongzuopian#爱情片4K$aiqingpian#科幻片4K$kehuanpian#恐怖片4K$kongbupian#剧情片4K$juqingpian#战争片4K$zhanzhengpian#纪录片4K$jilupian#动画片4K$donghuapian#电视剧4K$dianshiju#综艺4K$ZongYi"  }},
{"key": "csp_XBPQ_mp4cl","name": "mp4cl","type": 3,"api": "csp_XBPQ","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/mimang/cccc/raw/branch/master/mp4cl.json"},
{"key": "csp_XBPQ_ 97","name": "97","type": 3,"api": "csp_XBPQ","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/mimang/momo/raw/branch/master/97.json"},
{"key":"py_cctv","name":"🌏爱央视（PY)","type":3,"api":"py_cctv","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/xxpctv/nzhiban/raw/branch/master/p/py_cctv.py"},
{"key": "py_cctv","name": "🇨🇳CCTV大全(PY)","type": 3,"api": "py_cctv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/py/py_cctv2.py"},
{"key": "py_央视片库","name": "央视片库(PY)","type": 3,"api": "py_cctv","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/py/央视片库.py"},
{"key": "py_cctv_6","name": "🇨🇳CCTV(PY可搜索)","type": 3,"api": "py_cctv","searchable": 1,"quickSearch": 0,"filterable": 0,"ext": "https://agit.ai/lanhaidixingren/Tvbox/raw/branch/master/py/py_cctv.py"},
{"key": "py_bilimd","name": "B站影视(PY)","type": 3,"api": "py_bilimd","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/py/py_bilimd.py"},
{"key":"py_bilibili3","name":"B 站(PY)","type":3,"api":"py_bili","style":{ "type":"rect", "ratio":1.33 },"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/py_bilibili3.py"},
{"key":"py_douyin","name":"抖音直播(PY)","type":3,"api":"py_douyin","style":{ "type":"rect", "ratio":1.33 },"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/weigs/w/raw/branch/master/py/py_douyin.py"},
{"key": "py_kt30","name": "🐈卡通站(PY)","type": 3,"api": "py_kt30","searchable": 1,"quickSearch": 0,"filterable": 0,"ext": "https://agit.ai/lanhaidixingren/Tvbox/raw/branch/master/py/py_kt30.py"},
{"key": "py_gaoqing","name": "🐯高清资源(PY,绿化)","type": 3,"api": "py_gaoqing","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/lanhaidixingren/Tvbox/raw/branch/master/py/%E9%AB%98%E6%B8%85%E8%B5%84%E6%BA%90.py"},
{"key": "py_xinl","name": "🥡新浪资源(PY,绿化)","type": 3,"api": "py_xinl","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://agit.ai/lanhaidixingren/Tvbox/raw/branch/master/py/新浪资源.py"},
{"key": "drjs_bili","name": "哔站纪录片","type": 3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","searchable": 1,"changeable": 1,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/dr/%e5%93%94%e7%ab%99%e7%ba%aa%e5%bd%95%e7%89%87.js"},
{"key":"nm","name":"🥝农民","type":3,"api":"csp_XBPQ","ext":{"分类url":"https://m.xiangdao.me/vod-list-id-{cateId}-pg-{catePg}-order--by-{by}-class-0-year-{year}-letter--area-{area}-lang-.html;;akv","分类":"电影$1#电视剧$2#综艺$3#动漫$4"}},
{"key": "MTV转点播","name": "🎶16万MV","type": 3,"api": "https://agit.ai/66666/mv/raw/branch/master/live_min.js","ext": "https://agit.ai/66666/mv/raw/branch/master/live_min.txt"},
{"key":"drjs_A8音乐","name":"🎵A8音乐","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/lib/drpy.min.js","ext":"https://agit.ai/kvymin/drpy_js/raw/branch/master/JavaScript/A8音乐.js"},
{"key":"csp_YQKAPP","name":"🌎一起看","type":3,"api":"csp_YQKAPP","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"ext":"https://api-aws.11ty.top","jar":"https://agit.ai/xxpctv/m/raw/branch/master/py/YoursmileED3.jar;md5;9C583833C9809E13D924E3A2E27A2ED3"},
{"key": "dr_低端","name": "低端js","type": 3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://xhdwc.tk/js/ddys.js"},
{"key":"drpy_js骚火电影","name":"骚火电影[js]","type":3,"api":"https://xhdwc.tk/lib/drpy2.min.js","ext":"https://xhdwc.tk/js/骚火电影.js"},
{"key":"dr_快看","name":"🎈快看js","type":3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/py/快看.js"},
{"key":"快看","name":"🚴快看","type":3,"api":"csp_Kuaikan","searchable":1,"quickSearch":1,"filterable":1},
{"key": "drpy_js_360影视","name": "💘360(d)","type": 3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/py/360影视.js"},
{"key":"drpy_小Q","name":"QQ(d)","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/腾云.js"},
{"key":"drpy_忙果","name":"芒果(d)","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/百忙无果.js"},
{"key":"drpy_爱奇艺","name":"爱奇艺(d)","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/奇珍异兽.js"},
{"key":"drpy_U酷","name":"优酷js","type":3,"api":"https://agit.ai/sharers/fox/raw/branch/master/JS/lib/drpy2.min.js","playerType":2,"searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":"https://agit.ai/sharers/fox/raw/branch/master/JS/js/%e4%bc%98%e9%85%b7.js"},
{"key": "bbclili2","name": "🅱️b站xq(cli)","type": 4,"api": "http://home.jundie.top:9520/spider/cli_Bili?sort=dash,mp4","searchable": 1,"quickSearch": 0,"filterable": 1,"playerType": 2,"viewType": 1,"ext": {"type": "粤剧#相声小品#越剧#沪剧#滑稽戏","cookie": ""}},
{"key":"csp_Bttoo","name":"✌两个BT","type":3,"api":"csp_Bttwoo","searchable":1,"quickSearch":1,"filterable":1,"jar":"https://agit.ai/xxpctv/m/raw/branch/master/py/YoursmileED3.jar;md5;9C583833C9809E13D924E3A2E27A2ED3"},
{"key":"360","name":"💘360(d)","type":3,"api":"csp_SP33","searchable":1,"quickSearch":1,"filterable":1,"changeable":0},
{"key":"csp_Qtv","name":"🐧腾讯(d)","type": 3,"api":"csp_Qtv","searchable": 1,"quickSearch": 1,"filterable":1,"changeable":0},
{"key":"csp_Itv","name":"🥝爱奇艺(d)","type":3,"api":"csp_Itv","quickSearch":1,"searchable":1,"filterable":1,"changeable":0},
{"key":"csp_Mtv","name":"🍋芒果(d)","type":3,"api":"csp_Mtv","searchable":1,"quickSearch":1,"filterable":1,"changeable":0},
{"key":"csp_Czsapp","name":"🏭厂长","type":3,"api":"csp_Czsapp","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://www.czz9.com/"},
{"key": "py_bookreader","name": "有声小说t4","type": 4,"api": "https://api.azure.leuse.top/PythonT4/bookreader","searchable": 1,"changeable": 0},
{"key": "sbb", "name": "🍬素白白", "type": 1, "api": "https://drpyxxpctv.xxpctv.repl.co/vod?rule=%E7%B4%A0%E7%99%BD%E7%99%BD","categories": ["连续剧","国产剧","欧美剧","韩剧","动漫剧"]},
{"key":"Aid","name":"🚑急救教学","type":3,"api":"csp_FirstAid","searchable":0,"quickSearch":0,"filterable":0,"changeable":0},
{"key":"csp_Mayiys","name":"🐜蚂蚁","type":3,"api":"csp_Mayiys","searchable":1,"quickSearch":1,"filterable":0,"ext":"http://rzys.xyz"},
{ "key": "ff","name": "🌱非凡","type": 1,"api": "http://cj.ffzyapi.com/api.php/provide/vod/","playUrl": "","searchable": 1,"quickSearch": 1,"filterable": 1,"categories": ["国产剧"]},
{"key":"csp_XBPQ_骚火影视","name":"️☀️骚火影视","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/骚火影视.json"},
{"key": "csp_XYQBiu_TVB云播","name": "🌱TVB云播","type": 3,"api": "csp_XYQBiu","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/zhanglc1987/TV/raw/branch/master/XYQBiu/TVB云播.json"},
{"key":"dr_JRKAN直播","name":"⚡直播赛事","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/JRKAN.js"},
{"key":"dr_JRKAN直播2","name":"⚡直播赛事2","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/JRKANvs.js"},
{"key":"jp","name": "️🌎回放","type": 1,"api": "https://www.jipo.tv/api.php/provide/vod","searchable": 1,"quickSearch": 1,"filterable": 1,"categories":["体育","足球","篮球","斯诺克","国产剧","港台剧","纪录片"]},
{"key":"dr_兔小贝","name":"🐰兔小贝","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/1018610504/daoruaimi/raw/branch/master/js/%E5%85%94%E5%B0%8F%E8%B4%9D.js"},
{"key":"csp_XYQHiker_兔小贝2","name":"🐰兔小贝❷","type":3,"api":"csp_XYQHiker","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/xyqh/兔小贝2.json"},
{"key":"1080","name":"1080p","type":1,"api":"https://api.1080zyku.com/inc/api_mac10.php","searchable":0,"quickSearch":0,"categories":["国产剧","综艺","动漫","动画片","纪录片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","韩国剧","欧美剧","香港剧","泰国剧","日本剧","港台剧"]},
{"key":"58zy","name":"58影视","type":1,"api":"http://cps.pdscxz.cn/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1,"categories": ["电影","连续剧", "综艺","动漫"]},
{"key":"U酷资源","name":"U酷","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"categories":["综艺","动漫","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","国产剧","港澳剧","日剧","欧美剧","动漫电影","台湾剧","韩剧","泰剧","记录片"]},
{"key": "老年人频道","name": "⚡粤剧","type": 3,"api": "csp_Bili","searchable": 0,"quickSearch": 0,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/bil/yueju.json"},
{"key":"csp_Bili合集","name":"🌎综艺up","type": 3,"api": "csp_Bili","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/bil/Biliup.json"},
{"key":"csp_AppMr","name":"👻明明影视","type":3,"api":"csp_AppMr","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_xp_qiumi","name":"✌球迷","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/py_qm.py"},
{"key":"csp_Voflix","name":"🌀Voflix","type":3,"api":"csp_Voflix","searchable":1,"quickSearch":1,"filterable":1},
{"key":"纪录","name":"✨纪录","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/bil/%E7%BA%AA%E5%BD%95%E7%89%87.json"},
{"key": "赛车","name": "🚗赛车","type": 3,"api": "csp_Bili","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/xxpctv/m/raw/branch/master/bil/yueye.json"},
{"key":"csp_Anime1","name":"🌸动漫","type":3,"api":"csp_Anime1","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Dm84","name":"🚌动漫巴士","type":3,"api":"csp_Dm84","searchable":1,"quickSearch":1,"filterable":1},
{"key":"push_agent","name":"🍭推送","type":3,"api":"csp_Push","searchable":0,"quickSearch":0,"filterable":0,"ext": "http://127.0.0.1:9978/file/tvfan/token.txt+4k|auto|fhd"},
{"key":"csp_AList","name":"🅰AList网盘","type":3,"api":"csp_AList","searchable":1,"quickSearch":0,"filterable":1,"changeable":0,"ext":"https://download.kstore.space/download/4127/js/alist.json"},
{"key":"drpy_js_六月听书","name":"💧六月听书","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/六月听书.js","playerType":"2"},
{"key":"量子","name":"💢量子","type":0,"api":"https://cj.lziapi.com/api.php/provide/vod/at/xml/","searchable":1,"changeable":1,"categories":["国产动漫","日韩动漫","国产剧","韩国剧","日本剧","电影片","连续剧","综艺片","动漫片","动作片","喜剧片","爱情片","科幻片","恐怖片","剧情片","战争片","台湾剧","香港剧","欧美剧","记录片","海外剧","泰国剧","大陆综艺","港台综艺","日韩综艺","欧美综艺","欧美动漫","港台动漫","海外动漫","体育","足球","篮球","网球","斯诺克"]},
{"key":"csp_XBPQ_非凡资源","name":"💢非凡","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/uncle_ven/tvbox/raw/branch/master/profiles/json/XBPQ/非凡资源.json"},
{"key":"csp_XBPQ_量子资源","name":"💢量子","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/uncle_ven/tvbox/raw/branch/master/profiles/json/XBPQ/量子资源.json"},
{"key":"csp_XBPQ_奇优","name":"️💢奇优","type":3,"api":"csp_XBPQ","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/奇优.json"},
{"key": "黑狐","name": "🦊黑狐XB","type": 3,"searchable": 1,"quickSearch": 1,"playerType": "1","api": "csp_XBPQ","ext": {"站名":"黑狐影院","主页url":"http://fagmn.com","数组":"class=\"stui-vodlist__box\"&&</a","图片":"data-original=\"&&\"","标题":"title=\"&&\"","链接":"href=\"&&\"","嗅探词":".m3u8#v3.huoshanvod.com#v3-dy-o.zjcdn#sf16-sg.larksuitecdn.com#v.kd1.qq.com","过滤词":"/hls/#php","副标题":"<span class=\"pic-text text-right\">&&</span>","搜索url":"http://fagmn.com/search.php;post;searchword={wd}","搜索模式":"1","搜索数组":"<a class=\"v-thumb stui-vodlist__thumb&&</a>","搜索图片":"data-original=\"&&\"","搜索标题":"title=\"&&\"","搜索链接":"href=\"&&\"","搜索副标题":"<span class=\"pic-text text-right\">&&</span>","搜索后缀":"/view/","线路数组":"href=\"#down&&/a>[替换:奇异视频>>黑狐一线#优酷视频>>黑狐二线#搜狐视频>>黑狐三线#咪咕视频>>黑狐四线]","线路标题":">&&<","播放数组":"class=\"stui-content__playlist clearfix&&</ul>","状态":"地区：&&</p>","导演":"导演：&&</p>","主演":"主演：&&</p>","简介":"简介：&&</div>","播放列表":"<a&&/a>","播放标题":">&&<","播放链接":"href=\"&&\"","免嗅":"0","分类":"电影$1#电视剧$2#动漫$3#综艺$4","分类url":"http://fagmn.com/list/{cateId}_{catePg}.html?order=time"}},
{"key": "NOND","name": "🚀NOND简写","type": 3,"api": "csp_XBPQ","searchable": 1,"quickSearch": 1,"filterable": 1,
"ext": {"线路数组": "data-toggle=&&</li>","线路标题": ">&&</a >[替换:（>>共#）>>集][不包含:视频下载 (夸克网盘)#不要]","播放数组": "<ul class=\"stui-content__playlist&&</ul>","图片": "data-original=\"&&\"","链接": "href=\"&&\"","标题": "title=\"&&\"","副标题": "pic-text text-right\">&&</span>","简介": "class=\"detail-content\"style=*>&&</span>","搜索url": "https://novipnoad.vip/search/{wd}----------{catePg}---.html","分类url": "https://novipnoad.vip/show/{cateId}-{area}-{by}-{class}-----{catePg}---{year}.html;;mak", "分类": "短剧$21#电影$1#电视剧$2#综艺$4#动漫$3#解说$24#纪录片$30#体育比赛$20#足球$26#篮球$27#网球$28#斯诺克$29"}},
{"key":"JRKAN直播","name":"JRKAN直播","type":3,"api":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/lib/drpy.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/JRKAN直播.js"},
{"key":"dr_虎牙","name":"🐯虎牙","type":3,"api":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/lib/drpy2.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/虎牙直播.js"},
{"key":"虎牙直播","name":"🐯虎牙🚦","type":3,"api":"https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","style":{"type":"rect","ratio":1.597},"changeable":0,"ext":"https://agit.ai/1018610504/daoruaimi/raw/branch/master/js/%E8%99%8E%E7%89%99%E7%9B%B4%E6%92%AD.js"},
{"key": "csp_XYQBiu_斗鱼","name": "🐟斗鱼直播","type": 3,"api": "https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy.min.js","ext": "https://agit.ai/fantaiying/dr_py/raw/branch/main/js/斗鱼直播.js","searchable": 0,"quickSearch": 0,"changeable": 0},
{"key": "csp_XYQHiker_兔小贝","name":"兔小贝(XYQH)","type":3,"api":"csp_XYQHiker","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://agit.ai/kvymin/TVRule/raw/branch/main/XYQHiker/%E5%85%94%E5%B0%8F%E8%B4%9D.json"},
{"key":"dr_兔小贝2","name":"兔小贝","type":3,"api":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/lib/drpy2.min.js","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/js/兔小贝.js"},
{"key":"短视频","name":"☘️短视频","type":3,"api":"csp_XBPQ","searchable":0,"quickSearch":0,"filterable":1,"ext":{"主页url":"http://www.sharenice.net","直接播放":"1","嗅探词":".m3u8#m3u8?#.mp4#mp4?#ixigua#.czspp#.flv#.mp3#.m4a#?item/video#is_play_url=1#play/?#qianpailive","分类":"抖音&快手&微视&火山&场库&美拍&秒拍&全民&梨&好兔&开眼&美女&搞笑&社会&音乐&娱乐&影视&正能量&生活&动漫&萌系&美食&体育&游戏&明星&旅游&时尚","分类值":"douyin&kuaishou&weishi&huoshan&changku&meipai&miaopai&quanmin&lishipin&haotu&kaiyan&t-576O5aWz&t-5pCe56yR&t-56S+5Lya&t-6Z+z5LmQ&t-5aix5LmQ&t-5b2x6KeG&t-5q2j6IO96YeP&t-55Sf5rS7&t-5Yqo5ryr&t-6JCM57O7&t-576O6aOf&t-5L2T6IKy&t-5ri45oiP&t-5piO5pif&t-5peF5ri4&t-5pe25bCa","分类url":"http://www.sharenice.net/{cateId}?page={catePg}","二次截取":"class=\"item-box\">&&</ul>","数组":"<li&&</li>","图片":"data-original=\"&&\"","标题":"title=\"&&\"","链接":"href=\"&&\""}},
{"key":"蜻蜓FM1223","name":"🚦蜻蜓FM🚦","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","changeable":0,"ext":"https://agit.ai/1018610504/daoruaimi/raw/branch/master/js/%E8%9C%BB%E8%9C%93FM.js"},
{"key": "酷奇js","name": "🎤酷奇┃MV","type": 3,"api": "https://agit.ai/xxpctv/m/raw/branch/master/drp/drpy2.min.js","ext": "https://agit.ai/1018610504/daoruaimi/raw/branch/master/js/%E9%85%B7%E5%A5%87MV.js","style": {"type": "rect","ratio": 1.597},"searchable": 0,"quickSearch": 0,"changeable": 0},
{"key":"csp_xpath_A33","name":"🎸MTV","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":1,"ext":"http://home.jundie.top:81/TVBox/MaooXB/mtv.json"},
{"key":"B站","name":"🅱B站","type":3,"api":"csp_Bili","ext":"https://agit.ai/tae/t/raw/branch/master/x/bz.json"},
{"key":"美食","name":"哔哔合集","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://agit.ai/fantaiying/fty/raw/branch/master/json/bilibili.json"},
{"key":"csp_Biliych","name":"哔哔演唱会","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/fantaiying/fty/raw/branch/master/json/biliych.json"},
{"key":"blzb","name":"哔哩直播(dd)","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","changeable":0,"ext":"https://agit.ai/xxpctv/m/raw/branch/master/py/%e5%93%94%e5%93%a9%e7%9b%b4%e6%92%ad.js"},
{"key":"drpy_blzb","name":"🅱️哔哩zb","type":3,"api":"https://agit.ai/xxpctv/jdds/raw/branch/master/js/drpy2.min.js","ext":"https://agit.ai/1018610504/daoruaimi/raw/branch/master/js/%E5%93%94%E5%93%A9%E7%9B%B4%E6%92%AD.js"},
{"key": "csp_Bliyc学前","name": "🅱️学前教育(SP)","type": 3,"api": "csp_Bili","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://agit.ai/138001380000/MHQTV/raw/branch/master/BIBI/学前儿童.txt"},
{"key":"csp_Bili","name":"🅱️哔哩哔哩","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/Bili.json"},
{"key":"相声小品","name":"🅱️相声小品","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/Blixs.json"},
{"key":"戏曲","name":"🅱️戏曲","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/Blixq.json"},
{"key":"少儿","name":"🅱️少儿","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/少儿教育.json"},
{"key":"小学","name":"🅱️小学","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/小学课堂.json"},
{"key":"初中","name":"🅱️初中","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/初中课堂.json"},
{"key":"高中","name":"🅱️高中","type":3,"api":"csp_Bili","searchable":0,"quickSearch":0,"filterable":1,"ext":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/sub/高中课堂.json"}],
"parses": [{
		"name": "Web聚合",
		"type": 3,
		"url": "Web"
	},
{
		"name": "Json聚合",
		"type": 3,
		"url": "Demo"
	}, 
{"name":"弹幕解析","type":0,"url":"https://jiexi.555jiexi.net:555/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜","1905","ltnb","renrenmi","rx","rongxing"]}},	
{"name":"夜幕","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"-虾米-","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
{"name":"-云解析-","type":0,"url":"https://jx.yparse.com/index.php?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name":"-777-","type":0,"url":"https://jx.jsonplayer.com/player/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name":"-全看-","type":0,"url":"https://jx.quankan.app/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"}}},
{"name":"-爱豆-","type":0,"url":"https://jx.aidouer.net/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36","referer":"https://jiejie.uk/"}}},
{"name":"-咸鱼-","type":0,"url":"https://jx.xyflv.cc/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Linux; Android 13; V2049A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36","referer":"https://www.xyflv.cc/"}}},	
{"name": "解析1","type": 1,"url": "http://61.147.93.21:8090/index.php?url="},
{"name":"线路2","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"}}},
	{"name": "g9","type": 1,"url": "http://json.g9.pub:66/?url=","ext": {"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}}, 
{"name":"ckmov","type":0,"url":"https://yun.ckmov.com/?url="},
{"name":"🎯分享有爱","type":1,"url":"https://svip.cygc.xyz/api/?key=dVtcmaBX6lt954hcKJ&url="},
{"name":"💕推荐","type":1,"url":"http://42.157.129.144:2323/CH/caihong_1993138546.php?url="},
{"name": "分享智能","type": 1,"url": "http://json.84jia.com/home/api?type=ys&uid=335253&key=acefhmqsxEMPRVYZ26&url="},
{"name": "分享智能1","type": 1,"url": "http://119.91.123.253:2345/Api/yun.php?url="},
{"name": "分享自动","type":1,"url":"http://42.157.129.144:2323/CH/caihong_1993138546.php?url="},

{"name":"推荐💕","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"默认💕","url": "https://vip.lianfaka.com/vip/?url=","ext":{"header": 
 {"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1","Referer": "https://www.dy6g.com/"}}},
 {"name": "超解析", "type": 1, "url": "http://110.42.2.247:880/analysis/json/?uid=2384&my=bcijquvxAFKMUY0579&format=json&url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},  
{"name": "超聚合", "type": 1, "url": "http://110.42.2.247:880/analysis/json/?uid=2255&my=eimqrtwxBCDIKT2458&format=json&url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},
{"name":"高清解析1","type":1,"url":"https://vip.xuux.icu/home/api?type=ys&uid=1325731&key=adfgilmnpwzBDEJPY3&url=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"],"header":{"User-Agent":"Dart/3.0(dart:io)"}}},

{"name":"综合/B站/", "type":0,"url":"https://jx.jsonplayer.com/player/?url=", "showType":3},
 {"name": "777","type": 0,"url": "https://jx.777jiexi.com/player/?url="},
    {"name": "ok","type": 0,"url": "http://okjx.cc/?url="},
    {"name": "yp","type": 0,"url": "https://jx.yparse.com/index.php?url="},
    {"name": "boz","type": 0,"url": "https://jx.bozrc.com:4433/player/?url="},
    {"name": "aid","type": 0,"url": "https://jx.aidouer.net/?url="},
 {"name": "json","type": 0,"url": "https://jx.jsonplayer.com/player/?url="},
  {"name": "dyg","type": 0,"url": "http://hangup.tk:5705/parse/api/dyg.js?url="},
{"name": "芒果","type": 1,"url": "http://110.42.2.247:880/analysis/json/?uid=2255&my=bcdkloqxzEFGPRT168&format=json&url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header": {"User-Agent": "okhttp/4.1.0"}}}, 
{
		"name": "刚佬",
		"type": 1,
		"url": "http://json.g9.pub:66/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		} 
	}, {
		"name": "未知",
		"type": 1,
		"url": "https://vip.mosangkeji.com/api/?key=rRNvXAnOghBBLnC35c&url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"]
		} 
	}, {
		"name": "777",
		"type": 0,
		"url": "https://jx.777jiexi.com/player/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}   
	}, {
		"name": "bozrc",
		"type": 0,
		"url": "https://jx.bozrc.com:4433/player/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}   
	}, {
		"name": "zhanglang",
		"type": 0,
		"url": "https://jx.zhanlangbu.com/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}    
	}, {
		"name": "左岸",
		"type": 0,
		"url": "https://jx.jsonplayer.com/player/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}
		}   
	}, {
		"name": "ckmov",
		"type": 0,
		"url": "https://yun.ckmov.com/?url=",
		"ext": {
			"flag": ["qq", "腾讯", "qiyi", "爱奇艺", "奇艺", "youku", "优酷", "mgtv", "芒果", "letv", "乐视", "pptv", "PPTV", "sohu", "bilibili", "哔哩哔哩", "哔哩"]
		}  
	}],
   "lives": [{"group": "redirect","channels": [{"name": "live","urls": ["proxy://do=live&type=txt&ext=aHR0cHM6Ly9hZ2l0LmFpL3h4cGN0di9qZGRzL3Jhdy9icmFuY2gvbWFzdGVyL2pkL2pkZHMudHh0"]}]}],
   "doh":[{"name":"Google","url":"https://dns.google/dns-query","ips":["8.8.4.4","8.8.8.8"]},{"name":"Cloudflare","url":"https://cloudflare-dns.com/dns-query","ips":["1.1.1.1","1.0.0.1","2606:4700:4700::1111","2606:4700:4700::1001"]},{"name":"AdGuard","url":"https://dns.adguard.com/dns-query","ips":["94.140.14.140","94.140.14.141"]},{"name":"DNSWatch","url":"https://resolver2.dns.watch/dns-query","ips":["84.200.69.80","84.200.70.40"]},{"name":"Quad9","url":"https://dns.quad9.net/dns-quer","ips":["9.9.9.9","149.112.112.112"]}],
   "warningText": "有事做有所期待，日子就是幸福的。", 
   "rules":[{"name":"量子","hosts":["vip.lz","hd.lz"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.433333,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},{"name":"非凡","hosts":["vip.ffzy","hd.ffzy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.666667,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},{"name":"火山","hosts":["huoshan.com"],"regex":["item_id="]},{"name":"抖音","hosts":["douyin.com"],"regex":["is_play_url="]}],
 "flags":["youku","qq","QQ","iqiyi","qiyi","letv","sohu","tudou","pptv","PPTV","mgtv","ltnb","rx","SLYS4k","BYGA","BYGB","luanzi","dxzy","QEYSS","aliyun","AliS","122","chuangying","CL4K","xfyun","wuduzy","wasu","bilibili","renrenmi","xmm","xigua","m1905","funshion","优酷","芒果","腾讯","爱奇艺","奇艺","哔哩哔哩","哔哩","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频","FY","fy","FeiYun","feiyun","飞云"],
   "ijk":[{"group":"软解码","options":[{"category":4,"name":"opensles","value":"0"},{"category":4,"name":"overlay-format","value":"842225234"},{"category":4,"name":"framedrop","value":"1"},{"category":4,"name":"soundtouch","value":"1"},{"category":4,"name":"start-on-prepared","value":"1"},{"category":1,"name":"http-detect-rangeupport","value":"0"},{"category":1,"name":"fflags","value":"fastseek"},{"category":2,"name":"skip_loop_filter","value":"48"},{"category":4,"name":"reconnect","value":"1"},{"category":4,"name":"enable-accurateeek","value":"0"},{"category":4,"name":"mediacodec","value":"0"},{"category":4,"name":"mediacodec-auto-rotate","value":"0"},{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"},{"category":4,"name":"mediacodec-hevc","value":"0"},{"category":1,"name":"dns_cache_timeout","value":"600000000"}]},{"group":"硬解码","options":[{"category":4,"name":"opensles","value":"0"},{"category":4,"name":"overlay-format","value":"842225234"},{"category":4,"name":"framedrop","value":"1"},{"category":4,"name":"soundtouch","value":"1"},{"category":4,"name":"start-on-prepared","value":"1"},{"category":1,"name":"http-detect-rangeupport","value":"0"},{"category":1,"name":"fflags","value":"fastseek"},{"category":2,"name":"skip_loop_filter","value":"48"},{"category":4,"name":"reconnect","value":"1"},{"category":4,"name":"enable-accurateeek","value":"0"},{"category":4,"name":"mediacodec","value":"1"},{"category":4,"name":"mediacodec-auto-rotate","value":"1"},{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"},{"category":4,"name":"mediacodec-hevc","value":"1"},{"category":1,"name":"dns_cache_timeout","value":"600000000"}]}],
   "ads":["iqiyi.hbuioo.com","vip.ffzyad.com","wan.51img1.com","https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd","mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"],"daily_sentence" : "https://v1.hitokoto.cn/?c=i&max_length=20"}

